"""
Twilio_Messaging_V1 List Message Services Flow

Auto-generated by Integration Co-Worker
Task: List all message services
"""
from typing import Dict, Any, Optional
from integrations.clients.twilio_messaging_v1 import TwilioMessagingV1Client
from integrations.clients.twilio_messaging_v1 import IntegrationError


def list_message_services_flow(
    api_key: str,
    payload: Dict[str, Any],
    **kwargs: Any,
) -> Dict[str, Any]:
    """
    Execute the list message services workflow.
    
    This flow:
    1. Validates input parameters
    2. Calls the twilio_messaging_v1 API
    3. Transforms and returns the response
    
    Args:
        api_key: API authentication key
        payload: Request payload for the API containing:
            - ServiceSid: The SID of the Service to create the AlphaSender under
            - AlphaSenderId: The Alphanumeric Sender ID string
        **kwargs: Additional options (e.g., idempotency_key)
    
    Returns:
        Dict containing the API response with relevant fields:
            - success: Boolean indicating operation success
            - data: The API response data containing AlphaSender details
    
    Raises:
        ValueError: If required input is missing or invalid
        IntegrationError: If the API call fails
    """
    # Step 1: Validate input
    if not api_key:
        raise ValueError("api_key is required")
    
    if not payload:
        raise ValueError("payload is required")
    
    if not isinstance(payload, dict):
        raise ValueError("payload must be a dictionary")
    
    # Validate required payload fields
    required_fields = ["ServiceSid", "AlphaSenderId"]
    missing_fields = [field for field in required_fields if field not in payload]
    if missing_fields:
        raise ValueError(f"Missing required payload fields: {', '.join(missing_fields)}")
    
    service_sid = payload.get("ServiceSid")
    if not service_sid or not isinstance(service_sid, str):
        raise ValueError("ServiceSid must be a non-empty string")
    
    alpha_sender_id = payload.get("AlphaSenderId")
    if not alpha_sender_id or not isinstance(alpha_sender_id, str):
        raise ValueError("AlphaSenderId must be a non-empty string")
    
    # Step 2: Call the API
    client = TwilioMessagingV1Client(api_key=api_key)
    idempotency_key = kwargs.get("idempotency_key")
    
    try:
        response = client.create_alpha_sender(
            payload=payload,
            idempotency_key=idempotency_key,
        )
    except IntegrationError as e:
        raise IntegrationError(f"Failed to create alpha sender: {str(e)}") from e
    except Exception as e:
        raise IntegrationError(f"Unexpected error during API call: {str(e)}") from e
    
    # Step 3: Transform and return response
    if not response:
        raise IntegrationError("API returned empty response")
    
    return {
        "success": True,
        "data": response,
        "service_sid": service_sid,
        "alpha_sender_id": alpha_sender_id,
    }