from integration_coworker.graph.state import WorkflowState

def build_report(state: WorkflowState) -> WorkflowState:
    """
    Reads: All state fields
    Writes: report_markdown
    """
    lines = []
    
    lines.append("# Integration Co-Worker Report")
    lines.append("")
    
    # Header
    lines.append(f"**Run ID**: `{state.run_id or 'N/A'}`")
    lines.append(f"**Provider**: `{state.provider_code or 'unknown'}`")
    lines.append(f"**Task**: {state.task_description or 'N/A'}")
    lines.append("")
    
    # Spec ingestion
    lines.append("## Spec Ingestion")
    lines.append(f"- Spec documents: {len(state.spec_documents)}")
    lines.append(f"- Chunks: {len(state.doc_chunks)}")
    lines.append("")
    
    # Silver model
    lines.append("## Silver API Model")
    lines.append(f"- Endpoints: {len(state.endpoints)}")
    if state.endpoints:
        lines.append("### Endpoints:")
        for ep in state.endpoints[:5]:  # Show first 5
            lines.append(f"  - `{ep.method} {ep.path}` ({ep.operation_id})")
        if len(state.endpoints) > 5:
            lines.append(f"  - ... and {len(state.endpoints) - 5} more")
    lines.append(f"- Schemas: {len(state.schemas)}")
    lines.append(f"- Entities: {len(state.entities)}")
    lines.append(f"- Relationships: {len(state.relationships)}")
    lines.append("")
    
    # Gold workflow
    lines.append("## Integration Workflow")
    if state.integration_task:
        lines.append(f"**Task Slug**: `{state.integration_task.task_slug}`")
    lines.append(f"- Workflow nodes: {len(state.workflow_nodes)}")
    if state.workflow_nodes:
        lines.append("### Workflow Steps:")
        for node in state.workflow_nodes:
            label = node.config.get("label", node.node_key)
            description = node.config.get("description", "")
            lines.append(f"  {node.position + 1}. **{label}** ({node.node_type}): {description}")
    lines.append(f"- Workflow edges: {len(state.workflow_edges)}")
    lines.append(f"- Endpoint bindings: {len(state.endpoint_bindings)}")
    lines.append("")
    
    # Policies
    lines.append("## Policies")
    lines.append(f"- Total policies: {len(state.policies)}")
    if state.policies:
        policy_counts = {}
        for policy in state.policies:
            pt = policy.policy_type.value if hasattr(policy.policy_type, 'value') else str(policy.policy_type)
            policy_counts[pt] = policy_counts.get(pt, 0) + 1
        for policy_type, count in policy_counts.items():
            lines.append(f"  - {policy_type}: {count}")
    lines.append("")
    
    # Code generation
    lines.append("## Generated Code")
    lines.append(f"- Code artifacts: {len(state.code_artifacts)}")
    if state.code_artifacts:
        lines.append("### Artifacts:")
        for artifact in state.code_artifacts:
            lines.append(f"  - `{artifact.rel_path}` ({artifact.artifact_type}, {artifact.language})")
    lines.append("")
    
    # Repo integration
    if state.repo_changes:
        lines.append("## Repository Changes")
        created = state.repo_changes.files_created()
        updated = state.repo_changes.files_updated()
        lines.append(f"- Files to create: {len(created)}")
        for change in created:
            lines.append(f"  - `{change.rel_path}`")
        lines.append(f"- Files to update: {len(updated)}")
        for change in updated:
            lines.append(f"  - `{change.rel_path}`")
        lines.append("")
    
    # Persistence
    if state.persisted_ids:
        lines.append("## Persistence")
        status = state.persisted_ids.get("run_status", "unknown")
        lines.append(f"**Status**: {status}")
        if "would_persist" in state.persisted_ids:
            lines.append("*(Dry run - no actual persistence)*")
        lines.append("")
    
    # Errors
    if state.errors:
        lines.append("## Errors")
        for error in state.errors:
            lines.append(f"- {error}")
        lines.append("")
    
    # Completion
    lines.append("## Completed Steps")
    for step in state.completed_steps:
        lines.append(f"- {step}")
    lines.append("")
    
    lines.append("---")
    lines.append("*Generated by Integration Co-Worker*")
    
    state.report_markdown = "\n".join(lines)
    state.completed_steps.append("build_report")
    return state
