"""
Tests for Twilio_Messaging_V1 List Message Services Flow

Auto-generated by Integration Co-Worker
"""
import pytest
from unittest.mock import Mock, patch, MagicMock
from integrations.flows.twilio_messaging_v1_list_message_services import list_message_services_flow


class TestTwilioMessagingV1Flow:
    """Tests for the list message services flow."""
    
    def test_list_message_services_flow_success(self):
        """Test successful flow execution.
        
        Verifies that the flow correctly calls the client's create_alpha_sender
        method and returns a successful response with the expected data structure.
        """
        with patch('integrations.flows.twilio_messaging_v1_list_message_services.TwilioMessagingV1Client') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.create_alpha_sender.return_value = {
                "sid": "PN12345678901234567890123456789012",
                "service_sid": "MG12345678901234567890123456789012",
                "alpha_sender": "TestSender",
                "capabilities": ["SMS"],
                "date_created": "2024-01-01T00:00:00Z",
                "date_updated": "2024-01-01T00:00:00Z",
                "url": "https://messaging.twilio.com/v1/Services/MG123/AlphaSenders/PN123"
            }
            
            # Execute flow
            result = list_message_services_flow(
                api_key="test_api_key",
                payload={
                    "service_sid": "MG12345678901234567890123456789012",
                    "alpha_sender": "TestSender"
                },
            )
            
            # Verify
            assert result["success"] is True
            assert "data" in result
            assert result["data"]["sid"] == "PN12345678901234567890123456789012"
            assert result["data"]["alpha_sender"] == "TestSender"
            
            # Verify client was called correctly
            MockClient.assert_called_once_with(api_key="test_api_key")
            mock_client.create_alpha_sender.assert_called_once_with(
                service_sid="MG12345678901234567890123456789012",
                alpha_sender="TestSender"
            )
    
    def test_list_message_services_flow_missing_api_key(self):
        """Test flow raises error when api_key is missing.
        
        Validates that the flow properly validates the api_key parameter
        and raises a ValueError with an appropriate message when it's empty.
        """
        with pytest.raises(ValueError, match="api_key is required"):
            list_message_services_flow(
                api_key="",
                payload={"service_sid": "MG123", "alpha_sender": "Test"},
            )
    
    def test_list_message_services_flow_missing_payload(self):
        """Test flow raises error when payload is missing.
        
        Validates that the flow properly validates the payload parameter
        and raises a ValueError when it's empty or missing required fields.
        """
        with pytest.raises(ValueError, match="payload is required"):
            list_message_services_flow(
                api_key="test_api_key",
                payload={},
            )
    
    def test_list_message_services_flow_missing_service_sid(self):
        """Test flow raises error when service_sid is missing from payload.
        
        Ensures that required fields in the payload are validated and
        appropriate errors are raised when they're missing.
        """
        with pytest.raises(ValueError, match="service_sid.*required"):
            list_message_services_flow(
                api_key="test_api_key",
                payload={"alpha_sender": "TestSender"},
            )
    
    def test_list_message_services_flow_missing_alpha_sender(self):
        """Test flow raises error when alpha_sender is missing from payload.
        
        Ensures that all required payload fields are validated before
        making API calls.
        """
        with pytest.raises(ValueError, match="alpha_sender.*required"):
            list_message_services_flow(
                api_key="test_api_key",
                payload={"service_sid": "MG12345678901234567890123456789012"},
            )
    
    def test_list_message_services_flow_api_error(self):
        """Test flow handles API errors gracefully.
        
        Verifies that the flow properly catches and handles exceptions
        raised by the API client, returning an error response structure.
        """
        with patch('integrations.flows.twilio_messaging_v1_list_message_services.TwilioMessagingV1Client') as MockClient:
            # Setup mock to raise an exception
            mock_client = MockClient.return_value
            mock_client.create_alpha_sender.side_effect = Exception("API Error: Invalid credentials")
            
            # Execute flow and expect it to handle the error
            result = list_message_services_flow(
                api_key="test_api_key",
                payload={
                    "service_sid": "MG12345678901234567890123456789012",
                    "alpha_sender": "TestSender"
                },
            )
            
            # Verify error response
            assert result["success"] is False
            assert "error" in result
            assert "API Error" in result["error"]
    
    def test_list_message_services_flow_http_error(self):
        """Test flow handles HTTP errors appropriately.
        
        Validates that HTTP-specific errors (like 401, 404, 500) are
        properly caught and returned in a structured error response.
        """
        with patch('integrations.flows.twilio_messaging_v1_list_message_services.TwilioMessagingV1Client') as MockClient:
            # Setup mock to raise HTTP error
            mock_client = MockClient.return_value
            http_error = Exception("HTTP 401: Unauthorized")
            mock_client.create_alpha_sender.side_effect = http_error
            
            # Execute flow
            result = list_message_services_flow(
                api_key="test_api_key",
                payload={
                    "service_sid": "MG12345678901234567890123456789012",
                    "alpha_sender": "TestSender"
                },
            )
            
            # Verify error handling
            assert result["success"] is False
            assert "error" in result
            assert "401" in result["error"] or "Unauthorized" in result["error"]
    
    def test_list_message_services_flow_with_optional_params(self):
        """Test flow with optional parameters in payload.
        
        Verifies that the flow correctly handles additional optional
        parameters that may be included in the payload.
        """
        with patch('integrations.flows.twilio_messaging_v1_list_message_services.TwilioMessagingV1Client') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.create_alpha_sender.return_value = {
                "sid": "PN12345678901234567890123456789012",
                "service_sid": "MG12345678901234567890123456789012",
                "alpha_sender": "TestSender",
                "capabilities": ["SMS", "MMS"],
                "date_created": "2024-01-01T00:00:00Z",
                "date_updated": "2024-01-01T00:00:00Z",
                "url": "https://messaging.twilio.com/v1/Services/MG123/AlphaSenders/PN123"
            }
            
            # Execute flow with additional parameters
            result = list_message_services_flow(
                api_key="test_api_key",
                payload={
                    "service_sid": "MG12345678901234567890123456789012",
                    "alpha_sender": "TestSender",
                    "capabilities": ["SMS", "MMS"]
                },
            )
            
            # Verify
            assert result["success"] is True
            assert result["data"]["capabilities"] == ["SMS", "MMS"]
    
    def test_list_message_services_flow_empty_response(self):
        """Test flow handles empty API response.
        
        Ensures that the flow can handle cases where the API returns
        an empty or null response without crashing.
        """
        with patch('integrations.flows.twilio_messaging_v1_list_message_services.TwilioMessagingV1Client') as MockClient:
            # Setup mock with empty response
            mock_client = MockClient.return_value
            mock_client.create_alpha_sender.return_value = {}
            
            # Execute flow
            result = list_message_services_flow(
                api_key="test_api_key",
                payload={
                    "service_sid": "MG12345678901234567890123456789012",
                    "alpha_sender": "TestSender"
                },
            )
            
            # Verify it still returns success with empty data
            assert result["success"] is True
            assert result["data"] == {}
    
    def test_list_message_services_flow_none_api_key(self):
        """Test flow raises error when api_key is None.
        
        Validates that None values for api_key are properly rejected.
        """
        with pytest.raises(ValueError, match="api_key is required"):
            list_message_services_flow(
                api_key=None,
                payload={
                    "service_sid": "MG12345678901234567890123456789012",
                    "alpha_sender": "TestSender"
                },
            )
    
    def test_list_message_services_flow_none_payload(self):
        """Test flow raises error when payload is None.
        
        Validates that None values for payload are properly rejected.
        """
        with pytest.raises(ValueError, match="payload is required"):
            list_message_services_flow(
                api_key="test_api_key",
                payload=None,
            )