"""
Github Get Repository Info Flow

Auto-generated by Integration Co-Worker
Task: Get repository info
"""
from typing import Dict, Any, Optional
from integrations.clients.github import GithubClient
from integrations.clients.github import IntegrationError


def get_repository_info_flow(
    api_key: str,
    payload: Dict[str, Any],
    **kwargs: Any,
) -> Dict[str, Any]:
    """
    Execute the get repository info workflow.
    
    This flow retrieves a specific variable from a GitHub repository's Actions settings.
    The authenticated user must have collaborator access to the repository.
    
    This flow:
    1. Validates input parameters (owner, repo, name)
    2. Calls the GitHub API to get the repository variable
    3. Transforms and returns the response
    
    Args:
        api_key: GitHub API authentication token (requires 'repo' scope)
        payload: Request payload containing:
            - owner (str): The account owner of the repository (username or org name)
            - repo (str): The name of the repository
            - name (str): The name of the variable to retrieve
        **kwargs: Additional options:
            - idempotency_key (str, optional): Key for idempotent requests
    
    Returns:
        Dict containing:
            - success (bool): True if the operation succeeded
            - data (Dict): The API response with variable details including:
                - name: Variable name
                - value: Variable value
                - created_at: Creation timestamp
                - updated_at: Last update timestamp
    
    Raises:
        ValueError: If required input parameters are missing or invalid
        IntegrationError: If the API call fails (e.g., authentication error,
            insufficient permissions, variable not found, repository not found)
    
    Example:
        >>> result = get_repository_info_flow(
        ...     api_key="ghp_xxxxxxxxxxxx",
        ...     payload={
        ...         "owner": "octocat",
        ...         "repo": "hello-world",
        ...         "name": "MY_VARIABLE"
        ...     }
        ... )
        >>> print(result["data"]["value"])
    """
    # Step 1: Validate input
    if not api_key:
        raise ValueError("api_key is required")
    
    if not payload:
        raise ValueError("payload is required")
    
    # Validate required payload fields
    required_fields = ["owner", "repo", "name"]
    missing_fields = [field for field in required_fields if field not in payload]
    
    if missing_fields:
        raise ValueError(
            f"Missing required payload fields: {', '.join(missing_fields)}"
        )
    
    # Validate field values are not empty
    for field in required_fields:
        if not payload.get(field):
            raise ValueError(f"payload field '{field}' cannot be empty")
    
    # Validate field types
    if not isinstance(payload["owner"], str):
        raise ValueError("payload field 'owner' must be a string")
    
    if not isinstance(payload["repo"], str):
        raise ValueError("payload field 'repo' must be a string")
    
    if not isinstance(payload["name"], str):
        raise ValueError("payload field 'name' must be a string")
    
    # Step 2: Call the API
    client = GithubClient(api_key=api_key)
    idempotency_key = kwargs.get("idempotency_key")
    
    try:
        response = client.actions_get_repo_variable(
            payload=payload,
            idempotency_key=idempotency_key,
        )
    except IntegrationError as e:
        # Re-raise IntegrationError with additional context
        raise IntegrationError(
            f"Failed to get repository variable '{payload['name']}' "
            f"from {payload['owner']}/{payload['repo']}: {str(e)}"
        ) from e
    except Exception as e:
        # Wrap unexpected exceptions
        raise IntegrationError(
            f"Unexpected error while getting repository variable: {str(e)}"
        ) from e
    
    # Step 3: Transform and return response
    return {
        "success": True,
        "data": response,
    }