"""
integration-coworker-runtime

Lightweight runtime library for API clients generated by Integration Coworker.

This package provides reusable components for:
- Authentication (Bearer, API Key, Basic)
- Retry with exponential backoff
- Rate limiting (Token Bucket, Sliding Window)
- HTTP client with policies applied

Install: pip install integration-coworker-runtime
"""
from integration_coworker_runtime.client import IntegrationClient
from integration_coworker_runtime.http_client import IntegrationHttpClient
from integration_coworker_runtime.auth import (
    BaseAuth,
    NoAuth,
    BearerAuth,
    ApiKeyAuth,
    BasicAuth,
)
from integration_coworker_runtime.retry import (
    BaseRetry,
    NoRetry,
    ExponentialRetry,
)
from integration_coworker_runtime.rate_limit import (
    BaseRateLimiter,
    NoRateLimiter,
    TokenBucketRateLimiter,
    SlidingWindowRateLimiter,
)
from integration_coworker_runtime.exceptions import (
    IntegrationError,
    TransientIntegrationError,
    AuthIntegrationError,
)

__version__ = "0.1.0"

__all__ = [
    # Version
    "__version__",
    # Clients
    "IntegrationClient",
    "IntegrationHttpClient",
    # Auth
    "BaseAuth",
    "NoAuth",
    "BearerAuth",
    "ApiKeyAuth",
    "BasicAuth",
    # Retry
    "BaseRetry",
    "NoRetry",
    "ExponentialRetry",
    # Rate Limiting
    "BaseRateLimiter",
    "NoRateLimiter",
    "TokenBucketRateLimiter",
    "SlidingWindowRateLimiter",
    # Exceptions
    "IntegrationError",
    "TransientIntegrationError",
    "AuthIntegrationError",
]
