"""
LLM Codegen Path Smoke Test

Proves that generate_code_and_tests actually uses LLM output when validation passes.
Uses a recognizable sentinel to verify the LLM-generated code flows through to artifacts.
"""
import ast
import pytest
from pathlib import Path
from unittest.mock import MagicMock

from integration_coworker.api.entrypoint import design_and_generate_integration
from integration_coworker.api.types import IntegrationOptions


# Sentinel code that the LLM "returns" - recognizable and valid Python
SENTINEL_CLIENT_CODE = '''"""
Mock Payments API Client - SENTINEL LLM OUTPUT

Auto-generated by Integration Co-Worker
Provider: mock_payments
"""
from typing import Dict, Any, Optional
from integration_coworker.runtime.http_client import IntegrationHttpClient
from integration_coworker.runtime.exceptions import IntegrationError


class MockPaymentsClient:
    """SENTINEL_LLM_MARKER: This code came from the LLM, not the template."""
    
    def __init__(self, api_key: str, base_url: str = "https://api.example.com"):
        self.client = IntegrationHttpClient(
            base_url=base_url,
            api_key=api_key,
            timeout_s=30,
            retries=3,
        )
    
    def create_checkout_session(
        self,
        payload: Dict[str, Any],
        idempotency_key: Optional[str] = None,
    ) -> Dict[str, Any]:
        """SENTINEL: Create a checkout session via LLM-generated code."""
        headers = {}
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        
        response = self.client.request(
            "POST",
            "/v1/checkout/sessions",
            json=payload,
            headers=headers,
        )
        
        if response.status_code not in (200, 201):
            raise IntegrationError(
                f"API request failed: {response.status_code}"
            )
        
        return response.json()
'''


SENTINEL_FLOW_CODE = '''"""
Mock Payments Flow - SENTINEL LLM OUTPUT
"""
from typing import Dict, Any, Optional
from integrations.clients.mock_payments import MockPaymentsClient


def create_checkout_session_flow(
    api_key: str,
    payload: Dict[str, Any],
    **kwargs: Any,
) -> Dict[str, Any]:
    """SENTINEL_LLM_MARKER: This flow was generated by LLM."""
    if not api_key:
        raise ValueError("api_key is required")
    if not payload:
        raise ValueError("payload is required")
    
    client = MockPaymentsClient(api_key=api_key)
    response = client.create_checkout_session(
        payload=payload,
        idempotency_key=kwargs.get("idempotency_key"),
    )
    
    return {
        "success": True,
        "data": response,
    }
'''


class TestLLMCodegenPath:
    """
    Tests that prove the LLM is actually on the hot path for code generation.
    """
    
    def test_llm_output_flows_to_client_artifact(self, tmp_path, monkeypatch):
        """
        Prove that when LLM returns valid code, it flows through to the artifact.
        
        Strategy:
        1. Monkeypatch call_llm to return sentinel code with a recognizable marker
        2. Run design_and_generate_integration
        3. Assert the sentinel marker appears in the client artifact
        4. Assert the code still passes AST validation
        """
        call_count = {"client": 0, "flow": 0, "test": 0}
        
        def fake_call_llm(prompt: str, task_type: str = "default") -> str:
            """Fake LLM that returns sentinel code based on artifact type."""
            prompt_lower = prompt.lower()
            
            # Detect artifact type from prompt
            if "artifact type: client" in prompt_lower:
                call_count["client"] += 1
                return SENTINEL_CLIENT_CODE
            elif "artifact type: flow" in prompt_lower:
                call_count["flow"] += 1
                return SENTINEL_FLOW_CODE
            elif "artifact type: test" in prompt_lower:
                call_count["test"] += 1
                # Return something that won't pass validation so template is used
                return "# test code placeholder"
            
            return f"# Mock for: {task_type}"
        
        # Patch the call_llm function where it's imported
        monkeypatch.setattr(
            "integration_coworker.graph.nodes.generate_code_and_tests.call_llm",
            fake_call_llm
        )
        
        # Run the pipeline
        fixture_path = Path(__file__).parent / "fixtures" / "mock_payments_openapi.yaml"
        
        result = design_and_generate_integration(
            spec_refs=[str(fixture_path)],
            task_description="Create checkout session",
            provider_code="mock_payments",
            repo_root=str(tmp_path),
            options=IntegrationOptions(
                repo_integration_enabled=False,  # In-memory only
                dry_run=True,
            ),
        )
        
        # Verify call_llm was actually called for codegen
        assert call_count["client"] >= 1, "call_llm should be invoked for client artifact"
        assert call_count["flow"] >= 1, "call_llm should be invoked for flow artifact"
        
        # Find client artifact
        client_artifacts = [a for a in result.code_artifacts if a.artifact_type == "client"]
        assert len(client_artifacts) >= 1, "Should generate client artifact"
        
        client_content = client_artifacts[0].content
        
        # THE KEY ASSERTION: Our sentinel marker should appear in the artifact
        assert "SENTINEL_LLM_MARKER" in client_content, (
            "Client artifact should contain LLM-generated code with sentinel marker. "
            "This proves LLM output flows through when validation passes."
        )
        
        # Also verify it's valid Python
        try:
            ast.parse(client_content)
        except SyntaxError as e:
            pytest.fail(f"LLM-generated client code should be valid Python: {e}")
        
        # Verify flow artifact also has sentinel
        flow_artifacts = [a for a in result.code_artifacts if a.artifact_type == "flow"]
        assert len(flow_artifacts) >= 1
        
        flow_content = flow_artifacts[0].content
        assert "SENTINEL_LLM_MARKER" in flow_content, (
            "Flow artifact should contain LLM-generated code with sentinel marker."
        )
    
    def test_fallback_to_template_when_llm_returns_invalid(self, tmp_path, monkeypatch):
        """
        Prove that when LLM returns invalid code, we fall back to template.
        
        This tests the validation logic:
        - If LLM returns syntactically invalid code, use template
        - Template code should still be valid and usable
        """
        def fake_call_llm_invalid(prompt: str, task_type: str = "default") -> str:
            """Return syntactically invalid Python."""
            return "def broken(:\n    return # invalid syntax"
        
        monkeypatch.setattr(
            "integration_coworker.graph.nodes.generate_code_and_tests.call_llm",
            fake_call_llm_invalid
        )
        
        fixture_path = Path(__file__).parent / "fixtures" / "mock_payments_openapi.yaml"
        
        result = design_and_generate_integration(
            spec_refs=[str(fixture_path)],
            task_description="Create checkout session",
            provider_code="mock_payments",
            repo_root=str(tmp_path),
            options=IntegrationOptions(
                repo_integration_enabled=False,
                dry_run=True,
            ),
        )
        
        # Should still generate artifacts (using template fallback)
        assert len(result.code_artifacts) >= 2, "Should generate artifacts via template fallback"
        
        # All artifacts should be valid Python
        for artifact in result.code_artifacts:
            try:
                ast.parse(artifact.content)
            except SyntaxError:
                pytest.fail(
                    f"Template fallback for {artifact.artifact_type} should produce valid Python"
                )
        
        # Should NOT contain sentinel (we're using templates)
        client_artifacts = [a for a in result.code_artifacts if a.artifact_type == "client"]
        assert "SENTINEL_LLM_MARKER" not in client_artifacts[0].content
    
    def test_llm_called_with_rich_prompt_context(self, tmp_path, monkeypatch):
        """
        Verify that the prompt sent to LLM contains rich context.
        
        This proves our prompts.py prompt builder is actually used.
        """
        captured_prompts = []
        
        def capture_call_llm(prompt: str, task_type: str = "default") -> str:
            """Capture prompts for inspection."""
            captured_prompts.append(prompt)
            # Return mock response to trigger fallback
            return "# mock"
        
        monkeypatch.setattr(
            "integration_coworker.graph.nodes.generate_code_and_tests.call_llm",
            capture_call_llm
        )
        
        fixture_path = Path(__file__).parent / "fixtures" / "mock_payments_openapi.yaml"
        
        design_and_generate_integration(
            spec_refs=[str(fixture_path)],
            task_description="Create checkout session",
            provider_code="mock_payments",
            repo_root=str(tmp_path),
            options=IntegrationOptions(
                repo_integration_enabled=False,
                dry_run=True,
            ),
        )
        
        # Should have captured prompts for client, flow, test
        assert len(captured_prompts) >= 3, "Should call LLM at least 3 times (client, flow, test)"
        
        # Verify prompts contain rich context (from prompts.py)
        client_prompt = captured_prompts[0]
        
        # Should contain endpoint details
        assert "POST" in client_prompt or "post" in client_prompt.lower(), (
            "Prompt should include HTTP method"
        )
        assert "/v1/checkout/sessions" in client_prompt or "checkout" in client_prompt.lower(), (
            "Prompt should include endpoint path"
        )
        
        # Should contain provider context
        assert "mock_payments" in client_prompt.lower(), (
            "Prompt should include provider code"
        )
        
        # Should contain artifact-specific instructions
        assert "client" in client_prompt.lower(), (
            "Prompt should specify artifact type"
        )
        
        # Should contain skeleton code
        assert "class " in client_prompt or "def " in client_prompt, (
            "Prompt should include skeleton code"
        )
