"""
Tests for P2: Config File Generation

Tests for generate_docker_compose(), generate_env_template(), 
generate_settings_yaml(), and related utilities.
"""
import pytest

from integration_coworker.codegen.config_templates import (
    ServiceConfig,
    EnvVariable,
    generate_docker_compose,
    generate_env_template,
    generate_settings_yaml,
    generate_gitignore_additions,
)
from integration_coworker.domain.models import SourceSystem, Policy

# Mark all tests in this module as not needing database
pytestmark = pytest.mark.no_db


# ---------------------------------------------------------------------------
# Test: generate_docker_compose
# ---------------------------------------------------------------------------

class TestGenerateDockerCompose:
    """Tests for docker-compose.yml generation."""
    
    def test_generates_valid_yaml_structure(self):
        """Should generate valid docker-compose structure."""
        result = generate_docker_compose()
        
        assert "version: '3.8'" in result
        assert "services:" in result
        assert "volumes:" in result
        assert "networks:" in result
    
    def test_includes_postgres_by_default(self):
        """Should include PostgreSQL service by default."""
        result = generate_docker_compose()
        
        assert "postgres:" in result
        assert "pgvector/pgvector:pg16" in result
        assert "POSTGRES_USER:" in result
        assert "POSTGRES_PASSWORD:" in result
        assert "postgres_data:" in result
    
    def test_excludes_postgres_when_disabled(self):
        """Should exclude PostgreSQL when include_db=False."""
        result = generate_docker_compose(include_db=False)
        
        assert "postgres:" not in result
        assert "pgvector" not in result
    
    def test_includes_redis_when_enabled(self):
        """Should include Redis when include_redis=True."""
        result = generate_docker_compose(include_redis=True)
        
        assert "redis:" in result
        assert "redis:7-alpine" in result
        assert "redis_data:" in result
    
    def test_excludes_redis_by_default(self):
        """Should exclude Redis by default."""
        result = generate_docker_compose()
        
        assert "redis:" not in result
    
    def test_includes_custom_services(self):
        """Should include custom service configurations."""
        services = [
            ServiceConfig(
                name="api",
                image="myapp:latest",
                ports=["8080:8080"],
                environment={"PORT": "8080"},
                depends_on=["postgres"],
            )
        ]
        
        result = generate_docker_compose(services=services)
        
        assert "api:" in result
        assert "myapp:latest" in result
        assert "8080:8080" in result
        assert "PORT: 8080" in result
        assert "depends_on:" in result
    
    def test_custom_network_name(self):
        """Should use custom network name."""
        result = generate_docker_compose(network_name="custom-net")
        
        assert "custom-net:" in result
    
    def test_service_with_volumes(self):
        """Should include service volumes."""
        services = [
            ServiceConfig(
                name="app",
                image="app:latest",
                volumes=["app_data:/data", "./config:/etc/app"],
            )
        ]
        
        result = generate_docker_compose(services=services, include_db=False)
        
        assert "app_data:/data" in result
        assert "./config:/etc/app" in result
        assert "app_data:" in result  # Volume definition
    
    def test_service_with_healthcheck(self):
        """Should include service healthcheck."""
        services = [
            ServiceConfig(
                name="app",
                image="app:latest",
                healthcheck={"test": ["CMD", "curl", "-f", "http://localhost/health"]},
            )
        ]
        
        result = generate_docker_compose(services=services, include_db=False)
        
        assert "healthcheck:" in result


# ---------------------------------------------------------------------------
# Test: generate_env_template
# ---------------------------------------------------------------------------

class TestGenerateEnvTemplate:
    """Tests for .env.template generation."""
    
    def test_includes_header_comments(self):
        """Should include descriptive header comments."""
        result = generate_env_template()
        
        assert "# Integration Configuration" in result
        assert "Generated by integration_coworker" in result
        assert "Copy this file to .env" in result
    
    def test_includes_db_vars_by_default(self):
        """Should include database variables by default."""
        result = generate_env_template()
        
        assert "POSTGRES_USER=" in result
        assert "POSTGRES_PASSWORD=" in result
        assert "POSTGRES_DB=" in result
        assert "DATABASE_URL=" in result
    
    def test_excludes_db_vars_when_disabled(self):
        """Should exclude database variables when disabled."""
        result = generate_env_template(include_db=False)
        
        assert "POSTGRES_USER" not in result
        assert "DATABASE_URL" not in result
    
    def test_includes_llm_vars_by_default(self):
        """Should include LLM API variables by default."""
        result = generate_env_template()
        
        assert "OPENAI_API_KEY=" in result
        assert "AZURE_OPENAI" in result
    
    def test_excludes_llm_vars_when_disabled(self):
        """Should exclude LLM variables when disabled."""
        result = generate_env_template(include_llm=False)
        
        assert "OPENAI_API_KEY" not in result
    
    def test_includes_source_system_bearer_auth(self):
        """Should include bearer token for source system."""
        source = SourceSystem(
            id=1,
            code="stripe",
            name="Stripe",
            auth_type="bearer",
        )
        
        result = generate_env_template(source_system=source)
        
        assert "STRIPE_BEARER_TOKEN=" in result
    
    def test_includes_source_system_api_key_auth(self):
        """Should include API key for source system."""
        source = SourceSystem(
            id=1,
            code="sendgrid",
            name="SendGrid",
            auth_type="api_key",
        )
        
        result = generate_env_template(source_system=source)
        
        assert "SENDGRID_API_KEY=" in result
    
    def test_includes_source_system_oauth2_auth(self):
        """Should include OAuth2 credentials for source system."""
        source = SourceSystem(
            id=1,
            code="github",
            name="GitHub",
            auth_type="oauth2",
        )
        
        result = generate_env_template(source_system=source)
        
        assert "GITHUB_CLIENT_ID=" in result
        assert "GITHUB_CLIENT_SECRET=" in result
        assert "GITHUB_REDIRECT_URI=" in result
    
    def test_includes_source_system_basic_auth(self):
        """Should include basic auth credentials for source system."""
        source = SourceSystem(
            id=1,
            code="jira",
            name="Jira",
            auth_type="basic",
        )
        
        result = generate_env_template(source_system=source)
        
        assert "JIRA_USERNAME=" in result
        assert "JIRA_PASSWORD=" in result
    
    def test_includes_rate_limit_from_policy(self):
        """Should include rate limit config from policy."""
        policies = [
            Policy(
                id=1,
                task_id=1,
                policy_type="rate_limit",
                scope="workflow",
                config={"requests_per_second": 50},
            )
        ]
        
        result = generate_env_template(policies=policies)
        
        assert "RATE_LIMIT_RPS=50" in result
    
    def test_includes_additional_vars(self):
        """Should include additional custom variables."""
        additional = [
            EnvVariable(
                name="CUSTOM_VAR",
                description="Custom configuration",
                default="default_value",
            ),
            EnvVariable(
                name="SECRET_KEY",
                description="Secret key for encryption",
                required=True,
                secret=True,
            ),
        ]
        
        result = generate_env_template(additional_vars=additional)
        
        assert "CUSTOM_VAR=default_value" in result
        assert "# Custom configuration" in result
        assert "SECRET_KEY=" in result
        assert "(secret)" in result
    
    def test_includes_app_settings(self):
        """Should include common app settings."""
        result = generate_env_template()
        
        assert "LOG_LEVEL=INFO" in result
        assert "DEBUG=false" in result


# ---------------------------------------------------------------------------
# Test: generate_settings_yaml
# ---------------------------------------------------------------------------

class TestGenerateSettingsYaml:
    """Tests for settings.yaml generation."""
    
    def test_generates_valid_structure(self):
        """Should generate valid YAML structure."""
        result = generate_settings_yaml()
        
        assert "integration:" in result
        assert "version: '1.0'" in result
        assert "logging:" in result
        assert "retry:" in result
    
    def test_includes_source_system_config(self):
        """Should include source system configuration."""
        source = SourceSystem(
            id=1,
            code="stripe",
            name="Stripe API",
            base_url="https://api.stripe.com",
            auth_type="bearer",
        )
        
        result = generate_settings_yaml(source_system=source)
        
        assert "code: stripe" in result
        assert "name: Stripe API" in result
        assert "auth_type: bearer" in result
        assert "api.stripe.com" in result
    
    def test_includes_policies(self):
        """Should include policy configurations."""
        policies = [
            Policy(
                id=1,
                task_id=1,
                policy_type="retry",
                scope="workflow",
                config={"max_retries": 5},
            ),
        ]
        
        result = generate_settings_yaml(policies=policies)
        
        assert "policies:" in result
        assert "type: retry" in result
        assert "max_retries: 5" in result
    
    def test_includes_endpoints(self):
        """Should include endpoint paths."""
        endpoints = [
            "/v1/customers",
            "/v1/payments",
            "/v1/subscriptions",
        ]
        
        result = generate_settings_yaml(endpoints=endpoints)
        
        assert "endpoints:" in result
        assert "- /v1/customers" in result
        assert "- /v1/payments" in result
    
    def test_includes_retry_defaults(self):
        """Should include default retry configuration."""
        result = generate_settings_yaml()
        
        assert "max_attempts: 3" in result
        assert "backoff_factor: 2" in result
        assert "max_delay: 60" in result
    
    def test_includes_logging_config(self):
        """Should include logging configuration."""
        result = generate_settings_yaml()
        
        assert "level:" in result
        assert "format: json" in result


# ---------------------------------------------------------------------------
# Test: generate_gitignore_additions
# ---------------------------------------------------------------------------

class TestGenerateGitignoreAdditions:
    """Tests for .gitignore additions."""
    
    def test_includes_env_files(self):
        """Should include .env files."""
        result = generate_gitignore_additions()
        
        assert ".env" in result
        assert ".env.local" in result
    
    def test_includes_backup_files(self):
        """Should include backup files."""
        result = generate_gitignore_additions()
        
        assert "*.bak" in result
        assert ".integration_backups/" in result
    
    def test_includes_secrets(self):
        """Should include secret files."""
        result = generate_gitignore_additions()
        
        assert "*.pem" in result
        assert "*.key" in result
        assert "secrets/" in result


# ---------------------------------------------------------------------------
# Test: ServiceConfig and EnvVariable dataclasses
# ---------------------------------------------------------------------------

class TestDataclasses:
    """Tests for dataclass functionality."""
    
    def test_service_config_defaults(self):
        """ServiceConfig should have sensible defaults."""
        svc = ServiceConfig(name="test", image="test:latest")
        
        assert svc.ports == []
        assert svc.environment == {}
        assert svc.volumes == []
        assert svc.depends_on == []
        assert svc.command is None
        assert svc.healthcheck is None
    
    def test_env_variable_defaults(self):
        """EnvVariable should have sensible defaults."""
        var = EnvVariable(name="TEST", description="Test var")
        
        assert var.default is None
        assert var.required is True
        assert var.secret is False
    
    def test_service_config_with_all_fields(self):
        """ServiceConfig should accept all fields."""
        svc = ServiceConfig(
            name="app",
            image="app:latest",
            ports=["8080:8080"],
            environment={"DEBUG": "true"},
            volumes=["data:/data"],
            depends_on=["db"],
            command="python main.py",
            healthcheck={"test": ["CMD", "curl", "-f", "http://localhost/health"]},
        )
        
        assert svc.name == "app"
        assert svc.command == "python main.py"
        assert "DEBUG" in svc.environment
