"""
Tests for Github Get Repository Info Flow

Auto-generated by Integration Co-Worker
"""
import pytest
from unittest.mock import Mock, patch
from integrations.workflows.github_get_repository_info import get_repository_info_flow


class TestGithubFlow:
    """Tests for the get repository info flow."""
    
    def test_get_repository_info_flow_success(self):
        """Test successful flow execution.
        
        Verifies that the flow correctly calls the GitHub API client
        to retrieve repository variable information and returns the
        expected success response structure.
        """
        with patch('integrations.workflows.github_get_repository_info.GithubClient') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.actions_get_repo_variable.return_value = {
                "name": "TEST_VARIABLE",
                "value": "test_value_123",
                "created_at": "2024-01-15T10:30:00Z",
                "updated_at": "2024-01-15T10:30:00Z"
            }
            
            # Execute flow
            result = get_repository_info_flow(
                api_key="test_api_key",
                payload={
                    "owner": "test-owner",
                    "repo": "test-repo",
                    "name": "TEST_VARIABLE"
                },
            )
            
            # Verify
            assert result["success"] is True
            assert "data" in result
            assert result["data"]["name"] == "TEST_VARIABLE"
            assert result["data"]["value"] == "test_value_123"
            
            # Verify client was called correctly
            mock_client.actions_get_repo_variable.assert_called_once_with(
                owner="test-owner",
                repo="test-repo",
                name="TEST_VARIABLE"
            )
    
    def test_get_repository_info_flow_missing_api_key(self):
        """Test flow raises error when api_key is missing.
        
        Validates that the flow properly validates required credentials
        and raises a ValueError with an appropriate message when the
        API key is not provided.
        """
        with pytest.raises(ValueError, match="api_key is required"):
            get_repository_info_flow(
                api_key="",
                payload={
                    "owner": "test-owner",
                    "repo": "test-repo",
                    "name": "TEST_VARIABLE"
                },
            )
    
    def test_get_repository_info_flow_missing_payload(self):
        """Test flow raises error when payload is missing.
        
        Ensures that the flow validates the presence of required
        payload data and raises a ValueError when the payload is empty.
        """
        with pytest.raises(ValueError, match="payload is required"):
            get_repository_info_flow(
                api_key="test_api_key",
                payload={},
            )
    
    def test_get_repository_info_flow_missing_owner(self):
        """Test flow raises error when owner is missing from payload.
        
        Validates that all required fields in the payload are checked
        and appropriate errors are raised for missing owner parameter.
        """
        with pytest.raises(ValueError, match="owner.*required"):
            get_repository_info_flow(
                api_key="test_api_key",
                payload={
                    "repo": "test-repo",
                    "name": "TEST_VARIABLE"
                },
            )
    
    def test_get_repository_info_flow_missing_repo(self):
        """Test flow raises error when repo is missing from payload.
        
        Validates that all required fields in the payload are checked
        and appropriate errors are raised for missing repo parameter.
        """
        with pytest.raises(ValueError, match="repo.*required"):
            get_repository_info_flow(
                api_key="test_api_key",
                payload={
                    "owner": "test-owner",
                    "name": "TEST_VARIABLE"
                },
            )
    
    def test_get_repository_info_flow_missing_name(self):
        """Test flow raises error when variable name is missing from payload.
        
        Validates that all required fields in the payload are checked
        and appropriate errors are raised for missing name parameter.
        """
        with pytest.raises(ValueError, match="name.*required"):
            get_repository_info_flow(
                api_key="test_api_key",
                payload={
                    "owner": "test-owner",
                    "repo": "test-repo"
                },
            )
    
    def test_get_repository_info_flow_api_error(self):
        """Test flow handles API errors gracefully.
        
        Verifies that the flow properly handles and propagates errors
        from the GitHub API client, such as authentication failures
        or resource not found errors.
        """
        with patch('integrations.workflows.github_get_repository_info.GithubClient') as MockClient:
            # Setup mock to raise an exception
            mock_client = MockClient.return_value
            mock_client.actions_get_repo_variable.side_effect = Exception("API Error: Variable not found")
            
            # Execute flow and expect exception
            with pytest.raises(Exception, match="API Error: Variable not found"):
                get_repository_info_flow(
                    api_key="test_api_key",
                    payload={
                        "owner": "test-owner",
                        "repo": "test-repo",
                        "name": "NONEXISTENT_VARIABLE"
                    },
                )
    
    def test_get_repository_info_flow_unauthorized(self):
        """Test flow handles unauthorized access errors.
        
        Validates that the flow properly handles 401/403 errors when
        the provided credentials lack necessary permissions to access
        the repository variable.
        """
        with patch('integrations.workflows.github_get_repository_info.GithubClient') as MockClient:
            # Setup mock to raise unauthorized exception
            mock_client = MockClient.return_value
            mock_client.actions_get_repo_variable.side_effect = Exception("401 Unauthorized")
            
            # Execute flow and expect exception
            with pytest.raises(Exception, match="401 Unauthorized"):
                get_repository_info_flow(
                    api_key="test_api_key",
                    payload={
                        "owner": "test-owner",
                        "repo": "test-repo",
                        "name": "TEST_VARIABLE"
                    },
                )
    
    def test_get_repository_info_flow_with_special_characters(self):
        """Test flow handles repository and variable names with special characters.
        
        Ensures that the flow correctly processes names containing
        hyphens, underscores, and other valid special characters.
        """
        with patch('integrations.workflows.github_get_repository_info.GithubClient') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.actions_get_repo_variable.return_value = {
                "name": "MY_TEST_VAR_123",
                "value": "special-value",
                "created_at": "2024-01-15T10:30:00Z",
                "updated_at": "2024-01-15T10:30:00Z"
            }
            
            # Execute flow with special characters
            result = get_repository_info_flow(
                api_key="test_api_key",
                payload={
                    "owner": "test-org-123",
                    "repo": "my-test-repo",
                    "name": "MY_TEST_VAR_123"
                },
            )
            
            # Verify
            assert result["success"] is True
            assert result["data"]["name"] == "MY_TEST_VAR_123"
            
            # Verify client was called with correct parameters
            mock_client.actions_get_repo_variable.assert_called_once_with(
                owner="test-org-123",
                repo="my-test-repo",
                name="MY_TEST_VAR_123"
            )