"""
Tests for Stripe Create Checkout Session Flow

Auto-generated by Integration Co-Worker
"""
import pytest
from unittest.mock import Mock, patch, MagicMock
from integrations.workflows.stripe_create_checkout_session import create_checkout_session_flow


class TestStripeFlow:
    """Tests for the create checkout session flow."""
    
    def test_create_checkout_session_flow_success(self):
        """Test successful flow execution.
        
        Verifies that the flow correctly creates a checkout session
        when provided with valid API credentials and payload data.
        """
        with patch('integrations.workflows.stripe_create_checkout_session.StripeClient') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.post_checkout_sessions.return_value = {
                "id": "cs_test_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
                "object": "checkout.session",
                "status": "open",
                "url": "https://checkout.stripe.com/c/pay/test_session",
                "payment_status": "unpaid",
                "mode": "payment",
                "currency": "usd",
                "amount_total": 5000,
            }
            
            # Execute flow
            result = create_checkout_session_flow(
                api_key="test_api_key",
                payload={
                    "line_items": [
                        {
                            "price": "price_test123",
                            "quantity": 1,
                        }
                    ],
                    "mode": "payment",
                    "success_url": "https://example.com/success",
                    "cancel_url": "https://example.com/cancel",
                },
            )
            
            # Verify
            assert result["success"] is True
            assert "data" in result
            assert result.get("data", {}).get("id") == "cs_test_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
            assert result.get("data", {}).get("status") == "open"
            assert result.get("data", {}).get("object") == "checkout.session"
            
            # Verify client was called correctly
            MockClient.assert_called_once_with(api_key="test_api_key")
            mock_client.post_checkout_sessions.assert_called_once()
    
    def test_create_checkout_session_flow_missing_api_key(self):
        """Test flow raises error when api_key is missing.
        
        Validates that the flow properly handles missing API credentials
        and raises an appropriate ValueError.
        """
        with pytest.raises(ValueError, match="api_key is required"):
            create_checkout_session_flow(
                api_key="",
                payload={
                    "line_items": [{"price": "price_test123", "quantity": 1}],
                    "mode": "payment",
                    "success_url": "https://example.com/success",
                    "cancel_url": "https://example.com/cancel",
                },
            )
    
    def test_create_checkout_session_flow_missing_payload(self):
        """Test flow raises error when payload is missing.
        
        Ensures that the flow validates required payload data
        and raises ValueError when payload is empty or missing.
        """
        with pytest.raises(ValueError, match="payload is required"):
            create_checkout_session_flow(
                api_key="test_api_key",
                payload={},
            )
    
    def test_create_checkout_session_flow_api_error(self):
        """Test flow handles API errors gracefully.
        
        Verifies that the flow properly catches and handles
        exceptions raised by the Stripe API client.
        """
        with patch('integrations.workflows.stripe_create_checkout_session.StripeClient') as MockClient:
            # Setup mock to raise exception
            mock_client = MockClient.return_value
            mock_client.post_checkout_sessions.side_effect = Exception("API Error: Invalid request")
            
            # Execute flow and expect exception
            with pytest.raises(Exception, match="API Error: Invalid request"):
                create_checkout_session_flow(
                    api_key="test_api_key",
                    payload={
                        "line_items": [{"price": "price_test123", "quantity": 1}],
                        "mode": "payment",
                        "success_url": "https://example.com/success",
                        "cancel_url": "https://example.com/cancel",
                    },
                )
    
    def test_create_checkout_session_flow_with_subscription_mode(self):
        """Test flow with subscription mode checkout session.
        
        Validates that the flow correctly handles subscription-based
        checkout sessions with recurring payment configuration.
        """
        with patch('integrations.workflows.stripe_create_checkout_session.StripeClient') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.post_checkout_sessions.return_value = {
                "id": "cs_test_subscription123",
                "object": "checkout.session",
                "status": "open",
                "mode": "subscription",
                "payment_status": "unpaid",
                "subscription": "sub_test123",
            }
            
            # Execute flow
            result = create_checkout_session_flow(
                api_key="test_api_key",
                payload={
                    "line_items": [
                        {
                            "price": "price_monthly_test",
                            "quantity": 1,
                        }
                    ],
                    "mode": "subscription",
                    "success_url": "https://example.com/success",
                    "cancel_url": "https://example.com/cancel",
                },
            )
            
            # Verify
            assert result["success"] is True
            assert result["data"]["mode"] == "subscription"
            assert "subscription" in result["data"]
    
    def test_create_checkout_session_flow_with_customer_email(self):
        """Test flow with customer email pre-filled.
        
        Verifies that the flow correctly passes customer email
        to pre-fill the checkout form.
        """
        with patch('integrations.workflows.stripe_create_checkout_session.StripeClient') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.post_checkout_sessions.return_value = {
                "id": "cs_test_with_email",
                "object": "checkout.session",
                "status": "open",
                "customer_email": "customer@example.com",
            }
            
            # Execute flow
            result = create_checkout_session_flow(
                api_key="test_api_key",
                payload={
                    "line_items": [{"price": "price_test123", "quantity": 1}],
                    "mode": "payment",
                    "success_url": "https://example.com/success",
                    "cancel_url": "https://example.com/cancel",
                    "customer_email": "customer@example.com",
                },
            )
            
            # Verify
            assert result["success"] is True
            assert mock_client.post_checkout_sessions.called
    
    def test_create_checkout_session_flow_none_api_key(self):
        """Test flow raises error when api_key is None.
        
        Validates that None values for api_key are properly rejected.
        """
        with pytest.raises(ValueError, match="api_key is required"):
            create_checkout_session_flow(
                api_key=None,
                payload={
                    "line_items": [{"price": "price_test123", "quantity": 1}],
                    "mode": "payment",
                    "success_url": "https://example.com/success",
                    "cancel_url": "https://example.com/cancel",
                },
            )
    
    def test_create_checkout_session_flow_none_payload(self):
        """Test flow raises error when payload is None.
        
        Validates that None values for payload are properly rejected.
        """
        with pytest.raises(ValueError, match="payload is required"):
            create_checkout_session_flow(
                api_key="test_api_key",
                payload=None,
            )
    
    def test_create_checkout_session_flow_with_metadata(self):
        """Test flow with custom metadata.
        
        Verifies that the flow correctly passes custom metadata
        to the checkout session for tracking purposes.
        """
        with patch('integrations.workflows.stripe_create_checkout_session.StripeClient') as MockClient:
            # Setup mock
            mock_client = MockClient.return_value
            mock_client.post_checkout_sessions.return_value = {
                "id": "cs_test_metadata",
                "object": "checkout.session",
                "status": "open",
                "metadata": {
                    "order_id": "order_12345",
                    "customer_type": "premium",
                },
            }
            
            # Execute flow
            result = create_checkout_session_flow(
                api_key="test_api_key",
                payload={
                    "line_items": [{"price": "price_test123", "quantity": 1}],
                    "mode": "payment",
                    "success_url": "https://example.com/success",
                    "cancel_url": "https://example.com/cancel",
                    "metadata": {
                        "order_id": "order_12345",
                        "customer_type": "premium",
                    },
                },
            )
            
            # Verify
            assert result["success"] is True
            assert "metadata" in result["data"]
            assert mock_client.post_checkout_sessions.called