"""
Github API Client (Standalone)

Auto-generated by Integration Co-Worker (inline mode)
Provider: github
Endpoint: GET /repos/{owner}/{repo}/actions/variables/{name}

This is a FULLY SELF-CONTAINED client with no external dependencies
beyond Python stdlib and httpx.
"""
from typing import Dict, Any, Optional
import os
import logging
import time
import random
import threading

import httpx


class IntegrationError(Exception):
    """Base exception for integration errors."""
    pass


class GithubClient:
    """
    Client for Github API.
    
    Gets a specific variable in a repository.
    
    The authenticated user must have collaborator access to the repository to use this endpoint.
    OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
    
    Attributes:
        api_key: API key for authentication
        base_url: Base URL for the API
        timeout: Request timeout in seconds
    """
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: str = "https://api.github.com",
        timeout: float = 30.0,
    ):
        """
        Initialize the GithubClient.
        
        Args:
            api_key: API key for authentication (or set GITHUB_API_KEY env var)
            base_url: Base URL for the API
            timeout: Request timeout in seconds
        """
        self.api_key = api_key or os.environ.get("GITHUB_API_KEY", "")
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self._client = httpx.Client(timeout=timeout)
        self._logger = logging.getLogger(self.__class__.__name__)
    
    # Retry configuration
    _max_retries: int = 3
    _base_delay: float = 1.0
    _max_delay: float = 60.0
    _retryable_status_codes: set = {429, 500, 502, 503, 504}
    
    def _calculate_delay(self, attempt: int) -> float:
        """
        Calculate exponential backoff delay with jitter.
        
        Args:
            attempt: Current retry attempt number (0-indexed)
            
        Returns:
            Delay in seconds with jitter applied
        """
        delay = self._base_delay * (2 ** attempt)
        delay = min(delay, self._max_delay)
        # Add jitter (up to 25%)
        jitter = delay * 0.25 * random.uniform(-1, 1)
        return max(0, delay + jitter)
    
    def _should_retry(self, status_code: int) -> bool:
        """
        Check if status code is retryable.
        
        Args:
            status_code: HTTP status code
            
        Returns:
            True if the status code should trigger a retry
        """
        return status_code in self._retryable_status_codes

    # Rate limiting (token bucket)
    _rate_limit_rps: float = 10.0
    _rate_limit_burst: int = 20
    _rate_limit_tokens: float = 20.0
    _rate_limit_last_refill: float = 0.0
    _rate_limit_lock: Optional[threading.Lock] = None
    
    def _init_rate_limiter(self) -> None:
        """Initialize rate limiter state with thread-safe lock."""
        if self._rate_limit_lock is None:
            self._rate_limit_lock = threading.Lock()
            self._rate_limit_last_refill = time.monotonic()
            self._rate_limit_tokens = float(self._rate_limit_burst)
    
    def _acquire_rate_limit_token(self) -> None:
        """
        Block until rate limit allows request using token bucket algorithm.
        
        This method implements a thread-safe token bucket rate limiter that
        refills tokens at a constant rate and allows bursts up to the bucket size.
        """
        self._init_rate_limiter()
        while True:
            with self._rate_limit_lock:  # type: ignore[union-attr]
                now = time.monotonic()
                elapsed = now - self._rate_limit_last_refill
                new_tokens = elapsed * self._rate_limit_rps
                self._rate_limit_tokens = min(self._rate_limit_burst, self._rate_limit_tokens + new_tokens)
                self._rate_limit_last_refill = now
                
                if self._rate_limit_tokens >= 1.0:
                    self._rate_limit_tokens -= 1.0
                    return
                
                wait_time = (1.0 - self._rate_limit_tokens) / self._rate_limit_rps
            time.sleep(wait_time)

    def close(self):
        """Close the HTTP client and release resources."""
        self._client.close()
    
    def __enter__(self):
        """Context manager entry."""
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.close()
    
    def actions_get_repo_variable(
        self,
        owner: str,
        repo: str,
        name: str,
        idempotency_key: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Get a repository variable.
        
        Gets a specific variable in a repository. The authenticated user must have
        collaborator access to the repository to use this endpoint.
        
        OAuth app tokens and personal access tokens (classic) need the `repo` scope
        to use this endpoint.
        
        Args:
            owner: The account owner of the repository. The name is not case sensitive.
            repo: The name of the repository without the .git extension. The name is not case sensitive.
            name: The name of the variable.
            idempotency_key: Optional idempotency key for safe retries
        
        Returns:
            API response as dictionary containing the repository variable details
        
        Raises:
            IntegrationError: If the API request fails after all retry attempts
            ValueError: If required parameters are missing or invalid
        """
        # Validate required parameters
        if not owner:
            raise ValueError("Parameter 'owner' is required and cannot be empty")
        if not repo:
            raise ValueError("Parameter 'repo' is required and cannot be empty")
        if not name:
            raise ValueError("Parameter 'name' is required and cannot be empty")
        
        # Construct URL with path parameters
        url = f"{self.base_url}/repos/{owner}/{repo}/actions/variables/{name}"
        
        # Prepare headers
        headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key

        # Apply rate limiting
        self._acquire_rate_limit_token()

        # Retry loop with exponential backoff
        last_exception = None
        response = None
        
        for attempt in range(self._max_retries):
            try:
                self._logger.debug(f"Making GET request to {url} (attempt {attempt + 1}/{self._max_retries})")
                
                response = self._client.request(
                    "GET",
                    url,
                    headers=headers,
                )

                # Check for retryable status codes
                if self._should_retry(response.status_code):
                    if attempt < self._max_retries - 1:
                        delay = self._calculate_delay(attempt)
                        self._logger.warning(
                            f"Received retryable status {response.status_code}. "
                            f"Retrying after {delay:.2f}s (attempt {attempt + 1}/{self._max_retries})"
                        )
                        time.sleep(delay)
                        continue
                    else:
                        self._logger.error(
                            f"Max retries reached with status {response.status_code}"
                        )
                
                # Success or non-retryable error - break out of retry loop
                break
                
            except httpx.TransportError as e:
                last_exception = e
                if attempt < self._max_retries - 1:
                    delay = self._calculate_delay(attempt)
                    self._logger.warning(
                        f"Transport error: {str(e)}. "
                        f"Retrying after {delay:.2f}s (attempt {attempt + 1}/{self._max_retries})"
                    )
                    time.sleep(delay)
                else:
                    self._logger.error(f"Request failed after {self._max_retries} attempts: {str(e)}")
                    raise IntegrationError(
                        f"Request failed after {self._max_retries} attempts: {str(e)}"
                    ) from e
            except Exception as e:
                self._logger.error(f"Unexpected error during request: {str(e)}")
                raise IntegrationError(f"Unexpected error during request: {str(e)}") from e
        
        # Check if we have a response
        if response is None:
            raise IntegrationError("No response received after all retry attempts")
        
        # Handle response status codes
        if response.status_code == 200:
            # Success - return parsed JSON
            try:
                return response.json()
            except Exception as e:
                self._logger.error(f"Failed to parse JSON response: {str(e)}")
                raise IntegrationError(f"Failed to parse JSON response: {str(e)}") from e
        
        elif response.status_code == 204:
            # No content - return empty dict
            return {}
        
        elif response.status_code == 404:
            raise IntegrationError(
                f"Resource not found: Repository variable '{name}' not found in {owner}/{repo}"
            )
        
        elif response.status_code == 401:
            raise IntegrationError(
                "Authentication failed: Invalid or missing API key. "
                "Ensure GITHUB_API_KEY is set or api_key is provided."
            )
        
        elif response.status_code == 403:
            raise IntegrationError(
                "Access forbidden: Insufficient permissions. "
                "Ensure the token has 'repo' scope and collaborator access to the repository."
            )
        
        else:
            # Generic error for other status codes
            error_detail = response.text[:500] if response.text else "No error details"
            raise IntegrationError(
                f"API request failed with status {response.status_code}: {error_detail}"
            )