"""
Twilio_Messaging_V1 API Client (Standalone)

Auto-generated by Integration Co-Worker (inline mode)
Provider: twilio_messaging_v1
Endpoint: POST /v1/Services/{ServiceSid}/AlphaSenders

This is a FULLY SELF-CONTAINED client with no external dependencies
beyond Python stdlib and httpx.
"""
from typing import Dict, Any, Optional
import os
import logging
import time
import random
import threading

import httpx


class IntegrationError(Exception):
    """Base exception for integration errors."""
    pass


class TwilioMessagingV1Client:
    """
    Client for Twilio_Messaging_V1 API.
    
    POST /v1/Services/{ServiceSid}/AlphaSenders
    
    This client provides methods to interact with the Twilio Messaging V1 API,
    specifically for creating alpha senders for messaging services.
    
    Features:
        - Automatic retry with exponential backoff
        - Rate limiting using token bucket algorithm
        - Bearer token authentication
        - Idempotency key support
        - Comprehensive error handling
    
    Example:
        >>> client = TwilioMessagingV1Client(api_key="your_api_key")
        >>> response = client.create_alpha_sender(
        ...     service_sid="MGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        ...     payload={"alpha_sender": "YourBrand"}
        ... )
        >>> print(response)
    """
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: str = "https://api.twiliomessagingv1.com",
        timeout: float = 30.0,
    ):
        """
        Initialize the TwilioMessagingV1Client.
        
        Args:
            api_key: API key for authentication. If not provided, will attempt to
                read from TWILIO_MESSAGING_V1_API_KEY environment variable.
            base_url: Base URL for the API. Defaults to the production endpoint.
            timeout: Request timeout in seconds. Defaults to 30.0.
        
        Raises:
            IntegrationError: If no API key is provided and environment variable is not set.
        """
        self.api_key = api_key or os.environ.get("TWILIO_MESSAGING_V1_API_KEY", "")
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self._client = httpx.Client(timeout=timeout)
        self._logger = logging.getLogger(self.__class__.__name__)
        
        if not self.api_key:
            self._logger.warning(
                "No API key provided. Set TWILIO_MESSAGING_V1_API_KEY environment "
                "variable or pass api_key parameter."
            )
    
    # Retry configuration
    _max_retries: int = 3
    _base_delay: float = 1.0
    _max_delay: float = 60.0
    _retryable_status_codes: set = {429, 500, 502, 503, 504}
    
    def _calculate_delay(self, attempt: int) -> float:
        """
        Calculate exponential backoff delay with jitter.
        
        Uses exponential backoff (2^attempt * base_delay) with a maximum delay cap
        and adds random jitter to prevent thundering herd problems.
        
        Args:
            attempt: The current retry attempt number (0-indexed).
        
        Returns:
            Delay in seconds before the next retry attempt.
        """
        delay = self._base_delay * (2 ** attempt)
        delay = min(delay, self._max_delay)
        # Add jitter (up to 25%)
        jitter = delay * 0.25 * random.uniform(-1, 1)
        return max(0, delay + jitter)
    
    def _should_retry(self, status_code: int) -> bool:
        """
        Check if status code is retryable.
        
        Args:
            status_code: HTTP status code from the response.
        
        Returns:
            True if the request should be retried, False otherwise.
        """
        return status_code in self._retryable_status_codes

    # Rate limiting (token bucket)
    _rate_limit_rps: float = 10.0
    _rate_limit_burst: int = 20
    _rate_limit_tokens: float = 20.0
    _rate_limit_last_refill: float = 0.0
    _rate_limit_lock: Optional[threading.Lock] = None
    
    def _init_rate_limiter(self) -> None:
        """
        Initialize rate limiter state.
        
        Sets up the token bucket rate limiter with thread-safe locking.
        This method is idempotent and safe to call multiple times.
        """
        if self._rate_limit_lock is None:
            self._rate_limit_lock = threading.Lock()
            self._rate_limit_last_refill = time.monotonic()
            self._rate_limit_tokens = float(self._rate_limit_burst)
    
    def _acquire_rate_limit_token(self) -> None:
        """
        Block until rate limit allows request.
        
        Implements a token bucket algorithm to enforce rate limits.
        Tokens are refilled at a constant rate (_rate_limit_rps) up to
        a maximum burst size (_rate_limit_burst).
        
        This method will block the calling thread until a token is available.
        """
        self._init_rate_limiter()
        while True:
            with self._rate_limit_lock:  # type: ignore[union-attr]
                now = time.monotonic()
                elapsed = now - self._rate_limit_last_refill
                new_tokens = elapsed * self._rate_limit_rps
                self._rate_limit_tokens = min(
                    self._rate_limit_burst, 
                    self._rate_limit_tokens + new_tokens
                )
                self._rate_limit_last_refill = now
                
                if self._rate_limit_tokens >= 1.0:
                    self._rate_limit_tokens -= 1.0
                    return
                
                wait_time = (1.0 - self._rate_limit_tokens) / self._rate_limit_rps
            time.sleep(wait_time)

    def close(self):
        """
        Close the HTTP client.
        
        Releases any resources held by the underlying HTTP client.
        Should be called when the client is no longer needed.
        """
        self._client.close()
    
    def __enter__(self):
        """Context manager entry."""
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.close()
    
    def create_alpha_sender(
        self,
        service_sid: str,
        payload: Dict[str, Any],
        idempotency_key: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Create an alpha sender for a messaging service.
        
        POST /v1/Services/{ServiceSid}/AlphaSenders
        
        Creates a new alpha sender (alphanumeric sender ID) for the specified
        messaging service. Alpha senders allow you to send messages with a
        custom alphanumeric sender ID instead of a phone number.
        
        Args:
            service_sid: The unique identifier of the messaging service.
                Must be a valid Twilio Service SID (e.g., MGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX).
            payload: Request payload containing alpha sender configuration.
                Expected to contain fields like 'alpha_sender' with the desired
                alphanumeric sender ID.
            idempotency_key: Optional idempotency key for safe retries.
                If provided, the API will ensure that duplicate requests with
                the same key are not processed multiple times.
        
        Returns:
            API response as dictionary containing the created alpha sender details.
            Typical response includes fields like 'sid', 'alpha_sender', 'date_created', etc.
        
        Raises:
            IntegrationError: If the API request fails after all retry attempts,
                or if the response status code indicates an error.
            ValueError: If service_sid is empty or invalid.
        
        Example:
            >>> client = TwilioMessagingV1Client(api_key="your_api_key")
            >>> response = client.create_alpha_sender(
            ...     service_sid="MGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            ...     payload={"alpha_sender": "MyCompany"}
            ... )
            >>> print(response['sid'])
        """
        if not service_sid:
            raise ValueError("service_sid parameter is required and cannot be empty")
        
        url = f"{self.base_url}/v1/Services/{service_sid}/AlphaSenders"
        
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key

        # Apply rate limiting
        self._acquire_rate_limit_token()

        # Retry loop with exponential backoff
        last_exception = None
        response = None
        
        for attempt in range(self._max_retries):
            try:
                self._logger.debug(
                    f"Attempt {attempt + 1}/{self._max_retries}: POST {url}"
                )
                
                response = self._client.request(
                    "POST",
                    url,
                    headers=headers,
                    json=payload,
                )

                # Check for retryable status codes
                if self._should_retry(response.status_code):
                    if attempt < self._max_retries - 1:
                        delay = self._calculate_delay(attempt)
                        self._logger.warning(
                            f"Received retryable status {response.status_code}. "
                            f"Retrying after {delay:.2f}s"
                        )
                        time.sleep(delay)
                        continue
                    else:
                        self._logger.error(
                            f"Max retries reached with status {response.status_code}"
                        )
                
                # Success or non-retryable error - break out of retry loop
                break
                
            except httpx.TransportError as e:
                last_exception = e
                self._logger.warning(
                    f"Transport error on attempt {attempt + 1}/{self._max_retries}: {e}"
                )
                
                if attempt < self._max_retries - 1:
                    delay = self._calculate_delay(attempt)
                    self._logger.info(f"Retrying after {delay:.2f}s")
                    time.sleep(delay)
                else:
                    raise IntegrationError(
                        f"Request failed after {self._max_retries} attempts: {last_exception}"
                    )
            
            except Exception as e:
                # Non-retryable exception
                self._logger.error(f"Unexpected error during request: {e}")
                raise IntegrationError(f"Unexpected error: {e}")
        
        # Check if we have a response
        if response is None:
            raise IntegrationError(
                f"Request failed after {self._max_retries} attempts: {last_exception}"
            )
        
        # Check response status
        if response.status_code not in (200, 201, 204):
            error_detail = response.text[:500] if response.text else "No error details"
            self._logger.error(
                f"API request failed with status {response.status_code}: {error_detail}"
            )
            raise IntegrationError(
                f"API request failed: {response.status_code} - {error_detail}"
            )
        
        # Handle empty responses
        if response.status_code == 204 or not response.content:
            self._logger.debug("Received empty response (204 or no content)")
            return {}
        
        # Parse and return JSON response
        try:
            result = response.json()
            self._logger.debug(f"Successfully created alpha sender")
            return result
        except Exception as e:
            self._logger.error(f"Failed to parse JSON response: {e}")
            raise IntegrationError(f"Failed to parse response JSON: {e}")