"""
Stripe API Client (Standalone)

Auto-generated by Integration Co-Worker (inline mode)
Provider: stripe
Endpoint: POST /v1/checkout/sessions

This is a FULLY SELF-CONTAINED client with no external dependencies
beyond Python stdlib and httpx.
"""
from typing import Dict, Any, Optional
import os
import logging
import time
import random
import threading

import httpx


class IntegrationError(Exception):
    """Base exception for integration errors."""
    pass


class StripeClient:
    """
    Client for Stripe API.
    
    Create a Checkout Session
    
    This client provides methods to interact with the Stripe API, specifically
    for creating checkout sessions. It includes built-in retry logic with
    exponential backoff, rate limiting, and comprehensive error handling.
    
    Attributes:
        api_key: API key for authentication
        base_url: Base URL for the Stripe API
        timeout: Request timeout in seconds
    
    Example:
        >>> client = StripeClient(api_key="sk_test_...")
        >>> payload = {
        ...     "success_url": "https://example.com/success",
        ...     "cancel_url": "https://example.com/cancel",
        ...     "line_items": [{"price": "price_123", "quantity": 1}],
        ...     "mode": "payment"
        ... }
        >>> session = client.post_checkout_sessions(payload)
        >>> print(session["id"])
    """
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: str = "https://api.stripe.com",
        timeout: float = 30.0,
    ):
        """
        Initialize the StripeClient.
        
        Args:
            api_key: API key for authentication (or set STRIPE_API_KEY env var).
                    Should start with 'sk_test_' or 'sk_live_'.
            base_url: Base URL for the API. Defaults to Stripe's production API.
            timeout: Request timeout in seconds. Defaults to 30.0.
        
        Raises:
            ValueError: If no API key is provided via parameter or environment variable.
        """
        self.api_key = api_key or os.environ.get("STRIPE_API_KEY", "")
        if not self.api_key:
            self._logger = logging.getLogger(self.__class__.__name__)
            self._logger.warning("No API key provided. Set STRIPE_API_KEY or pass api_key parameter.")
        
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self._client = httpx.Client(timeout=timeout)
        self._logger = logging.getLogger(self.__class__.__name__)
    
    # Retry configuration
    _max_retries: int = 3
    _base_delay: float = 1.0
    _max_delay: float = 60.0
    _retryable_status_codes: set = {429, 500, 502, 503, 504}
    
    def _calculate_delay(self, attempt: int) -> float:
        """
        Calculate exponential backoff delay with jitter.
        
        Uses exponential backoff (2^attempt * base_delay) with a maximum cap
        and adds random jitter to prevent thundering herd problems.
        
        Args:
            attempt: Current retry attempt number (0-indexed).
        
        Returns:
            Delay in seconds before next retry attempt.
        """
        delay = self._base_delay * (2 ** attempt)
        delay = min(delay, self._max_delay)
        # Add jitter (up to 25%)
        jitter = delay * 0.25 * random.uniform(-1, 1)
        return max(0, delay + jitter)
    
    def _should_retry(self, status_code: int) -> bool:
        """
        Check if status code is retryable.
        
        Args:
            status_code: HTTP status code from the response.
        
        Returns:
            True if the request should be retried, False otherwise.
        """
        return status_code in self._retryable_status_codes

    # Rate limiting (token bucket)
    _rate_limit_rps: float = 10.0
    _rate_limit_burst: int = 20
    _rate_limit_tokens: float = 20.0
    _rate_limit_last_refill: float = 0.0
    _rate_limit_lock: Optional[threading.Lock] = None
    
    def _init_rate_limiter(self) -> None:
        """
        Initialize rate limiter state.
        
        Sets up the token bucket rate limiter with thread-safe locking.
        This is called lazily on first use to avoid unnecessary overhead.
        """
        if self._rate_limit_lock is None:
            self._rate_limit_lock = threading.Lock()
            self._rate_limit_last_refill = time.monotonic()
            self._rate_limit_tokens = float(self._rate_limit_burst)
    
    def _acquire_rate_limit_token(self) -> None:
        """
        Block until rate limit allows request.
        
        Implements a token bucket algorithm to enforce rate limits.
        Tokens are refilled at a constant rate (_rate_limit_rps) up to
        a maximum burst size (_rate_limit_burst).
        
        This method blocks until a token is available, ensuring that
        requests don't exceed the configured rate limit.
        """
        self._init_rate_limiter()
        while True:
            with self._rate_limit_lock:  # type: ignore[union-attr]
                now = time.monotonic()
                elapsed = now - self._rate_limit_last_refill
                new_tokens = elapsed * self._rate_limit_rps
                self._rate_limit_tokens = min(
                    self._rate_limit_burst, 
                    self._rate_limit_tokens + new_tokens
                )
                self._rate_limit_last_refill = now
                
                if self._rate_limit_tokens >= 1.0:
                    self._rate_limit_tokens -= 1.0
                    return
                
                wait_time = (1.0 - self._rate_limit_tokens) / self._rate_limit_rps
            time.sleep(wait_time)

    def close(self):
        """
        Close the HTTP client.
        
        Releases any resources held by the underlying HTTP client.
        Should be called when the client is no longer needed.
        """
        self._client.close()
    
    def __enter__(self):
        """Context manager entry."""
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.close()
    
    def post_checkout_sessions(
        self,
        payload: Dict[str, Any],
        idempotency_key: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Create a Checkout Session.
        
        Creates a Checkout Session object that enables customers to complete
        a purchase. The session contains information about the line items,
        payment methods, and URLs for success/cancel redirects.
        
        Args:
            payload: Request payload containing checkout session parameters.
                    Required fields typically include:
                    - success_url: URL to redirect after successful payment
                    - cancel_url: URL to redirect if customer cancels
                    - line_items: List of items to purchase
                    - mode: Payment mode ('payment', 'subscription', or 'setup')
                    See Stripe API documentation for complete field list.
            idempotency_key: Optional idempotency key for safe retries.
                           If provided, Stripe will ensure the request is
                           processed exactly once, even if submitted multiple times.
        
        Returns:
            API response as dictionary containing the created checkout session.
            Includes fields like:
            - id: Unique identifier for the session
            - url: URL to redirect the customer to complete checkout
            - payment_status: Current payment status
            - customer: Customer ID if applicable
        
        Raises:
            IntegrationError: If the API request fails after all retry attempts,
                            or if the response status code indicates an error.
                            The error message includes the status code and
                            response body (truncated to 200 characters).
        
        Example:
            >>> payload = {
            ...     "success_url": "https://example.com/success",
            ...     "cancel_url": "https://example.com/cancel",
            ...     "line_items": [{
            ...         "price": "price_1234567890",
            ...         "quantity": 1
            ...     }],
            ...     "mode": "payment"
            ... }
            >>> session = client.post_checkout_sessions(payload)
            >>> print(f"Checkout URL: {session['url']}")
        """
        url = f"{self.base_url}/v1/checkout/sessions"
        
        headers = {
            "Content-Type": "application/x-www-form-urlencoded"
        }
        
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key

        # Apply rate limiting
        self._acquire_rate_limit_token()

        # Retry loop with exponential backoff
        last_exception = None
        response = None
        
        for attempt in range(self._max_retries):
            try:
                response = self._client.request(
                    "POST",
                    url,
                    headers=headers,
                    json=payload,
                )

                # Check for retryable status codes
                if response.status_code in self._retryable_status_codes:
                    if attempt < self._max_retries - 1:
                        delay = self._calculate_delay(attempt)
                        self._logger.warning(
                            f"Retrying after {delay:.2f}s (status {response.status_code}, "
                            f"attempt {attempt + 1}/{self._max_retries})"
                        )
                        time.sleep(delay)
                        continue
                    else:
                        # Last attempt failed with retryable status
                        break
                else:
                    # Non-retryable status code, break immediately
                    break
                    
            except httpx.TransportError as e:
                last_exception = e
                if attempt < self._max_retries - 1:
                    delay = self._calculate_delay(attempt)
                    self._logger.warning(
                        f"Retrying after {delay:.2f}s (transport error: {str(e)}, "
                        f"attempt {attempt + 1}/{self._max_retries})"
                    )
                    time.sleep(delay)
                else:
                    raise IntegrationError(
                        f"Request failed after {self._max_retries} attempts: {last_exception}"
                    )
        
        # If we exhausted retries due to transport errors
        if response is None:
            raise IntegrationError(
                f"Request failed after {self._max_retries} attempts: {last_exception}"
            )
        
        # Check response status
        if response.status_code not in (200, 201, 204):
            error_detail = response.text[:200] if response.text else "No error details"
            raise IntegrationError(
                f"API request failed: {response.status_code} - {error_detail}"
            )
        
        # Handle empty responses
        if response.status_code == 204 or not response.content:
            return {}
        
        try:
            return response.json()
        except Exception as e:
            self._logger.error(f"Failed to parse JSON response: {e}")
            raise IntegrationError(f"Invalid JSON response: {str(e)}")