#!/bin/bash
# =============================================================================
# Integration Co-Worker Demo Script
# =============================================================================
# 
# This script demonstrates the full capabilities of the Integration Co-Worker:
# 
# 1. Fetches a real OpenAPI spec (Twilio API v2010)
# 2. Uses real LLM calls (GPT-4 + Claude Sonnet 4) for understanding and codegen
# 3. Persists all data to PostgreSQL with pgvector (via Docker)
# 4. Generates standalone Python code with inline retry, rate limiting
# 5. Writes files to a target repository
# 6. Tracks everything in LangSmith for observability
#
# Prerequisites:
#   - Docker installed and running
#   - OPENAI_API_KEY set
#   - ANTHROPIC_API_KEY set
#   - LANGSMITH_API_KEY set (optional, for tracing)
#   - Python 3.11+ with venv activated
#
# Usage:
#   ./scripts/demo-twilio-sms.sh [target-dir]
#
# Example:
#   ./scripts/demo-twilio-sms.sh /tmp/my-project
#
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Load environment variables from .env file if it exists
if [ -f "$PROJECT_ROOT/.env" ]; then
    echo -e "${BLUE}📄 Loading environment from .env file...${NC}"
    set -a  # automatically export all variables
    source "$PROJECT_ROOT/.env"
    set +a
fi

# Target directory - default to the UPlant testing repo
TARGET_DIR="${1:-/Users/julianbartosz/git/schoolwork/UPlant/testing-solver-agentic-spec-coworker}"

echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║          INTEGRATION CO-WORKER DEMO - Twilio SMS                  ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
echo -e "${BLUE}🔍 Checking prerequisites...${NC}"

if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${RED}❌ OPENAI_API_KEY is not set${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ OPENAI_API_KEY is set${NC}"

if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo -e "${RED}❌ ANTHROPIC_API_KEY is not set${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ ANTHROPIC_API_KEY is set${NC}"

# LangSmith/LangChain tracing - support both variable names
if [ -n "$LANGCHAIN_API_KEY" ]; then
    export LANGSMITH_API_KEY="$LANGCHAIN_API_KEY"
fi
if [ -n "$LANGSMITH_API_KEY" ] || [ -n "$LANGCHAIN_API_KEY" ]; then
    echo -e "${GREEN}  ✓ LangSmith tracing enabled (project: ${LANGCHAIN_PROJECT:-default})${NC}"
else
    echo -e "${YELLOW}  ⚠ LANGCHAIN_API_KEY not set (tracing disabled)${NC}"
fi

# Check Docker is running
if ! docker info >/dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running${NC}"
    echo -e "${YELLOW}   Start Docker Desktop or run: open -a Docker${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ Docker is running${NC}"

# Start PostgreSQL via Docker Compose if not already running
echo -e "${BLUE}🐳 Starting PostgreSQL with pgvector via Docker Compose...${NC}"
docker compose up -d db 2>/dev/null || docker-compose up -d db

# Wait for PostgreSQL to be ready
echo -e "${BLUE}   Waiting for PostgreSQL to be ready...${NC}"
for i in {1..30}; do
    if docker compose exec -T db pg_isready -U integration -d integration_coworker >/dev/null 2>&1; then
        echo -e "${GREEN}  ✓ PostgreSQL is ready${NC}"
        break
    fi
    if [ $i -eq 30 ]; then
        echo -e "${RED}❌ PostgreSQL failed to start${NC}"
        docker compose logs db
        exit 1
    fi
    sleep 1
done

echo ""

# Create target directory
echo -e "${BLUE}📁 Creating target directory: ${TARGET_DIR}${NC}"
mkdir -p "$TARGET_DIR"

# Create requirements.txt with the runtime package
echo -e "${BLUE}📦 Creating requirements.txt with integration-coworker-runtime...${NC}"
cat > "$TARGET_DIR/requirements.txt" << 'EOF'
# Integration Co-Worker Runtime Dependencies
# Generated by demo-twilio-sms.sh

# Core HTTP client
httpx>=0.24.0

# Integration Co-Worker Runtime (optional - for runtime policy mode)
# Install from local package:
#   pip install /path/to/solver-agentic-spec-coworker/packages/integration-coworker-runtime
# Or when published to PyPI:
#   integration-coworker-runtime>=0.1.0

# Note: The generated code uses --standalone mode which includes all policies inline.
# This means httpx is the only required dependency for the generated client.
EOF
echo -e "${GREEN}  ✓ Created requirements.txt${NC}"
echo ""

# Change to project root
cd "$PROJECT_ROOT"

# Run the integration
echo -e "${BLUE}🚀 Running Integration Co-Worker...${NC}"
echo ""
echo -e "${YELLOW}Task: Send an SMS message to a phone number${NC}"
echo -e "${YELLOW}Spec: Twilio API v2010 (197 endpoints)${NC}"
echo -e "${YELLOW}Mode: Standalone (inline policies, no runtime deps)${NC}"
echo ""
echo -e "${CYAN}This will:${NC}"
echo -e "  1. Fetch and parse the Twilio OpenAPI spec"
echo -e "  2. Use GPT-4 to understand the task"
echo -e "  3. Query the Knowledge Graph for matching patterns"
echo -e "  4. Use Claude Sonnet 4 to generate code"
echo -e "  5. Write files to ${TARGET_DIR}"
echo -e "  6. Validate generated code syntax"
echo ""

# Activate venv if not already
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate 2>/dev/null || true
fi

# Run the CLI
python -m integration_coworker.cli run \
    --spec-ref "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json" \
    --task "Send an SMS message to a phone number" \
    --repo-root "$TARGET_DIR" \
    --standalone \
    --verbose || true  # Continue even if there are non-fatal errors

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ DEMO COMPLETE!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo ""

# Show generated files
echo -e "${BLUE}📄 Generated Files:${NC}"
find "$TARGET_DIR" -name "*.py" -type f | while read file; do
    lines=$(wc -l < "$file" | tr -d ' ')
    echo -e "  ${GREEN}✓${NC} $file (${lines} lines)"
done
echo ""

# Verify syntax
echo -e "${BLUE}🔍 Verifying Python Syntax:${NC}"
find "$TARGET_DIR" -name "*.py" -type f | while read file; do
    if python3 -m py_compile "$file" 2>/dev/null; then
        echo -e "  ${GREEN}✓${NC} $(basename "$file")"
    else
        echo -e "  ${RED}✗${NC} $(basename "$file")"
    fi
done
echo ""

# Run tests
echo -e "${BLUE}🧪 Running Generated Tests:${NC}"
cd "$TARGET_DIR"
if python3 -c "
import sys
sys.path.insert(0, 'src')

# Test imports
from integrations.flows.raw_send_sms_message import send_sms_message_flow
from integrations.clients.raw import RawClient, IntegrationError

# Test 1: Missing api_key
try:
    send_sms_message_flow(api_key='', payload={'FriendlyName': 'Test'})
except ValueError as e:
    if 'api_key' not in str(e).lower():
        raise
    print('  ✓ Test 1: api_key validation')

# Test 2: Empty payload
try:
    send_sms_message_flow(api_key='test', payload={})
except ValueError as e:
    if 'payload' not in str(e).lower():
        raise
    print('  ✓ Test 2: payload validation')

# Test 3: Mock API call with success
from unittest.mock import patch, MagicMock
with patch('integrations.flows.raw_send_sms_message.RawClient') as MockClient:
    mock_instance = MagicMock()
    mock_instance.create_account.return_value = {'sid': 'AC123', 'status': 'active'}
    MockClient.return_value = mock_instance
    result = send_sms_message_flow(api_key='key', payload={'FriendlyName': 'Test'})
    assert result['success'] is True
    print('  ✓ Test 3: Mock API call')

# Test 4: Client instantiation
client = RawClient(api_key='test_key', base_url='https://api.example.com')
assert client.api_key == 'test_key'
print('  ✓ Test 4: Client instantiation')

print()
print('All tests passed!')
" 2>&1; then
    echo ""
else
    echo -e "${RED}  Some tests failed${NC}"
fi

cd "$PROJECT_ROOT"

echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                        DEMO SUMMARY                               ║${NC}"
echo -e "${CYAN}╠═══════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║  Target Directory: ${NC}${TARGET_DIR}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}║  Generated Code:${NC}"
echo -e "${CYAN}║    • Client:  src/integrations/clients/raw.py${NC}"
echo -e "${CYAN}║    • Flow:    src/integrations/flows/raw_send_sms_message.py${NC}"
echo -e "${CYAN}║    • Tests:   tests/integrations/test_raw_send_sms_message.py${NC}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}║  Features:${NC}"
echo -e "${CYAN}║    ✓ Fully standalone (only depends on httpx)${NC}"
echo -e "${CYAN}║    ✓ Inline retry with exponential backoff${NC}"
echo -e "${CYAN}║    ✓ Inline rate limiting (token bucket)${NC}"
echo -e "${CYAN}║    ✓ Input validation${NC}"
echo -e "${CYAN}║    ✓ Error handling${NC}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}║  To use in your project:${NC}"
echo -e "${CYAN}║    cd ${TARGET_DIR}${NC}"
echo -e "${CYAN}║    pip install -r requirements.txt${NC}"
echo -e "${CYAN}║    export RAW_API_KEY=your_twilio_credentials${NC}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Show LangSmith link if available
if [ -n "$LANGSMITH_API_KEY" ] || [ -n "$LANGCHAIN_API_KEY" ]; then
    echo -e "${BLUE}📊 View traces in LangSmith: https://smith.langchain.com${NC}"
    echo ""
fi
