#!/bin/bash
# =============================================================================
# Integration Co-Worker Demo Script - OpenAI Chat Completions
# =============================================================================
# 
# This script demonstrates the full capabilities of the Integration Co-Worker:
# 
# 1. Fetches a real OpenAPI spec (OpenAI API)
# 2. Uses real LLM calls (GPT-4 + Claude Sonnet 4) for understanding and codegen
# 3. Persists all data to PostgreSQL with pgvector (via Docker)
# 4. Generates standalone Python code with inline retry, rate limiting
# 5. Writes files to a target repository
# 6. Tracks everything in LangSmith for observability
#
# Prerequisites:
#   - Docker installed and running
#   - OPENAI_API_KEY set
#   - ANTHROPIC_API_KEY set
#   - LANGCHAIN_API_KEY set (optional, for tracing)
#   - Python 3.11+ with venv activated
#
# Usage:
#   ./scripts/demo-openai-chat.sh [target-dir]
#
# Example:
#   ./scripts/demo-openai-chat.sh /tmp/my-project
#
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Load environment variables from .env file if it exists
if [ -f "$PROJECT_ROOT/.env" ]; then
    echo -e "${BLUE}📄 Loading environment from .env file...${NC}"
    set -a  # automatically export all variables
    source "$PROJECT_ROOT/.env"
    set +a
fi

# Target directory - default to the UPlant testing repo
TARGET_DIR="${1:-/Users/julianbartosz/git/schoolwork/UPlant/testing-solver-agentic-spec-coworker}"

echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      INTEGRATION CO-WORKER DEMO - OpenAI Chat Completions         ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
echo -e "${BLUE}🔍 Checking prerequisites...${NC}"

if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${RED}❌ OPENAI_API_KEY is not set${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ OPENAI_API_KEY is set${NC}"

if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo -e "${RED}❌ ANTHROPIC_API_KEY is not set${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ ANTHROPIC_API_KEY is set${NC}"

# LangSmith/LangChain tracing - support both variable names
if [ -n "$LANGCHAIN_API_KEY" ]; then
    export LANGSMITH_API_KEY="$LANGCHAIN_API_KEY"
fi
if [ -n "$LANGSMITH_API_KEY" ] || [ -n "$LANGCHAIN_API_KEY" ]; then
    echo -e "${GREEN}  ✓ LangSmith tracing enabled (project: ${LANGCHAIN_PROJECT:-default})${NC}"
else
    echo -e "${YELLOW}  ⚠ LANGCHAIN_API_KEY not set (tracing disabled)${NC}"
fi

# Check Docker is running
if ! docker info >/dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running${NC}"
    echo -e "${YELLOW}   Start Docker Desktop or run: open -a Docker${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ Docker is running${NC}"

# Start PostgreSQL via Docker Compose if not already running
echo -e "${BLUE}🐳 Starting PostgreSQL with pgvector via Docker Compose...${NC}"
cd "$PROJECT_ROOT"
docker compose up -d db 2>/dev/null || docker-compose up -d db

# Wait for PostgreSQL to be ready
echo -e "${BLUE}   Waiting for PostgreSQL to be ready...${NC}"
for i in {1..30}; do
    if docker compose exec -T db pg_isready -U integration -d integration_coworker >/dev/null 2>&1; then
        echo -e "${GREEN}  ✓ PostgreSQL is ready${NC}"
        break
    fi
    if [ $i -eq 30 ]; then
        echo -e "${RED}❌ PostgreSQL failed to start${NC}"
        docker compose logs db
        exit 1
    fi
    sleep 1
done

echo ""

# Create target directory
echo -e "${BLUE}📁 Creating target directory: ${TARGET_DIR}${NC}"
mkdir -p "$TARGET_DIR"

# Create requirements.txt with the runtime package
echo -e "${BLUE}📦 Creating requirements.txt...${NC}"
cat > "$TARGET_DIR/requirements.txt" << 'EOF'
# Integration Co-Worker Runtime Dependencies
# Generated by demo-openai-chat.sh

# Core HTTP client
httpx>=0.24.0

# Note: The generated code uses --standalone mode which includes all policies inline.
# This means httpx is the only required dependency for the generated client.
EOF
echo -e "${GREEN}  ✓ Created requirements.txt${NC}"
echo ""

# Change to project root
cd "$PROJECT_ROOT"

# Run the integration
echo -e "${BLUE}🚀 Running Integration Co-Worker...${NC}"
echo ""
echo -e "${YELLOW}Task: Create a chat completion with the OpenAI API${NC}"
echo -e "${YELLOW}Spec: OpenAI API (official spec)${NC}"
echo -e "${YELLOW}Mode: Standalone (inline policies, no runtime deps)${NC}"
echo ""
echo -e "${CYAN}This will:${NC}"
echo -e "  1. Fetch and parse the OpenAI API spec"
echo -e "  2. Use GPT-4 to understand the task"
echo -e "  3. Query the Knowledge Graph for matching patterns"
echo -e "  4. Use Claude Sonnet 4 to generate code"
echo -e "  5. Write files to ${TARGET_DIR}"
echo -e "  6. Validate generated code syntax"
echo ""

# Activate venv if not already
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate 2>/dev/null || true
fi

# Run the CLI with OpenAI spec
# Using the OpenAI API spec from Stainless (well-documented version)
python -m integration_coworker.cli run \
    --spec-ref "https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml" \
    --task "Create a chat completion with the OpenAI API" \
    --repo-root "$TARGET_DIR" \
    --standalone \
    --verbose || true  # Continue even if there are non-fatal errors

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ DEMO COMPLETE!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo ""

# Show generated files
echo -e "${BLUE}📄 Generated Files:${NC}"
find "$TARGET_DIR" -name "*.py" -type f 2>/dev/null | while read file; do
    lines=$(wc -l < "$file" | tr -d ' ')
    echo -e "  ${GREEN}✓${NC} $file (${lines} lines)"
done
echo ""

# Verify syntax
echo -e "${BLUE}🔍 Verifying Python Syntax:${NC}"
find "$TARGET_DIR" -name "*.py" -type f 2>/dev/null | while read file; do
    if python3 -m py_compile "$file" 2>/dev/null; then
        echo -e "  ${GREEN}✓${NC} $(basename "$file")"
    else
        echo -e "  ${RED}✗${NC} $(basename "$file")"
    fi
done
echo ""

# Run basic tests on generated code
echo -e "${BLUE}🧪 Running Generated Tests:${NC}"
cd "$TARGET_DIR"

# Find the generated flow file dynamically
FLOW_FILE=$(find src -name "*.py" -path "*/flows/*" ! -name "__init__.py" 2>/dev/null | head -1)
CLIENT_FILE=$(find src -name "*.py" -path "*/clients/*" ! -name "__init__.py" 2>/dev/null | head -1)

if [ -n "$FLOW_FILE" ] && [ -n "$CLIENT_FILE" ]; then
    # Extract module names
    FLOW_MODULE=$(echo "$FLOW_FILE" | sed 's|src/||' | sed 's|/|.|g' | sed 's|\.py$||')
    CLIENT_MODULE=$(echo "$CLIENT_FILE" | sed 's|src/||' | sed 's|/|.|g' | sed 's|\.py$||')
    
    echo -e "  ${CYAN}Testing: $FLOW_MODULE${NC}"
    
    python3 -c "
import sys
sys.path.insert(0, 'src')

# Dynamic imports
import importlib
flow_module = importlib.import_module('$FLOW_MODULE')
client_module = importlib.import_module('$CLIENT_MODULE')

# Get the client class (usually named *Client)
client_class = None
for name in dir(client_module):
    if name.endswith('Client') and name != 'Client':
        client_class = getattr(client_module, name)
        break

if client_class is None:
    # Try just 'RawClient' or similar
    for name in ['RawClient', 'OpenaiClient', 'Client']:
        if hasattr(client_module, name):
            client_class = getattr(client_module, name)
            break

# Get the flow function (usually ends with _flow)
flow_func = None
for name in dir(flow_module):
    if name.endswith('_flow') and callable(getattr(flow_module, name)):
        flow_func = getattr(flow_module, name)
        break

# Test 1: Client instantiation
if client_class:
    try:
        client = client_class(api_key='test_key', base_url='https://api.openai.com')
        print('  ✓ Test 1: Client instantiation')
    except Exception as e:
        print(f'  ✗ Test 1: Client instantiation failed: {e}')
else:
    print('  ⚠ Test 1: No client class found')

# Test 2: Flow function exists
if flow_func:
    print(f'  ✓ Test 2: Flow function found: {flow_func.__name__}')
else:
    print('  ⚠ Test 2: No flow function found')

# Test 3: Empty api_key validation
if flow_func:
    try:
        flow_func(api_key='', payload={'messages': [{'role': 'user', 'content': 'test'}]})
        print('  ✗ Test 3: Empty api_key should raise ValueError')
    except ValueError as e:
        if 'api_key' in str(e).lower():
            print('  ✓ Test 3: api_key validation')
        else:
            print(f'  ⚠ Test 3: Unexpected error: {e}')
    except Exception as e:
        print(f'  ⚠ Test 3: Unexpected exception: {type(e).__name__}: {e}')

# Test 4: Empty payload validation
if flow_func:
    try:
        flow_func(api_key='test', payload={})
        print('  ✗ Test 4: Empty payload should raise ValueError')
    except ValueError as e:
        if 'payload' in str(e).lower():
            print('  ✓ Test 4: payload validation')
        else:
            print(f'  ⚠ Test 4: Unexpected error: {e}')
    except Exception as e:
        print(f'  ⚠ Test 4: Unexpected exception: {type(e).__name__}: {e}')

# Test 5: Mock API call
if flow_func and client_class:
    from unittest.mock import patch, MagicMock
    
    # Get the client module path for patching
    client_path = f'{flow_module.__name__}.{client_class.__name__}'
    
    try:
        with patch(client_path) as MockClient:
            mock_instance = MagicMock()
            # Mock a successful response
            mock_instance.create_chat_completion.return_value = {
                'id': 'chatcmpl-123',
                'choices': [{'message': {'content': 'Hello!'}}]
            }
            # Also try other common method names
            mock_instance.create.return_value = mock_instance.create_chat_completion.return_value
            mock_instance.post.return_value = mock_instance.create_chat_completion.return_value
            MockClient.return_value = mock_instance
            
            result = flow_func(
                api_key='test_key',
                payload={'model': 'gpt-4', 'messages': [{'role': 'user', 'content': 'Hello'}]}
            )
            if result.get('success'):
                print('  ✓ Test 5: Mock API call')
            else:
                print(f'  ⚠ Test 5: Result: {result}')
    except Exception as e:
        print(f'  ⚠ Test 5: Mock test skipped: {type(e).__name__}')

print()
print('Tests completed!')
" 2>&1 || echo -e "${YELLOW}  Some tests may have failed - check output above${NC}"
else
    echo -e "${YELLOW}  No flow/client files found to test${NC}"
fi

cd "$PROJECT_ROOT"

echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                        DEMO SUMMARY                               ║${NC}"
echo -e "${CYAN}╠═══════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║  Target Directory: ${NC}${TARGET_DIR}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}║  API: OpenAI Chat Completions${NC}"
echo -e "${CYAN}║  Task: Create a chat completion${NC}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}║  Generated Code:${NC}"
echo -e "${CYAN}║    • Client:  src/integrations/clients/*.py${NC}"
echo -e "${CYAN}║    • Flow:    src/integrations/flows/*.py${NC}"
echo -e "${CYAN}║    • Tests:   tests/integrations/*.py${NC}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}║  Features:${NC}"
echo -e "${CYAN}║    ✓ Fully standalone (only depends on httpx)${NC}"
echo -e "${CYAN}║    ✓ Inline retry with exponential backoff${NC}"
echo -e "${CYAN}║    ✓ Inline rate limiting (token bucket)${NC}"
echo -e "${CYAN}║    ✓ Input validation${NC}"
echo -e "${CYAN}║    ✓ Error handling${NC}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}║  To use in your project:${NC}"
echo -e "${CYAN}║    cd ${TARGET_DIR}${NC}"
echo -e "${CYAN}║    pip install -r requirements.txt${NC}"
echo -e "${CYAN}║    export OPENAI_API_KEY=your_api_key${NC}"
echo -e "${CYAN}║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Show LangSmith link if available
if [ -n "$LANGSMITH_API_KEY" ] || [ -n "$LANGCHAIN_API_KEY" ]; then
    echo -e "${BLUE}📊 View traces in LangSmith: https://smith.langchain.com${NC}"
    echo ""
fi
