"""
Config Templates - Generate docker-compose.yml and .env templates.

P2: Config File Generation

This module provides templates for generating configuration files that
support the integration workflow:
- docker-compose.yml for container orchestration
- .env template for environment variables
- settings.yaml for application configuration
"""
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any

from integration_coworker.domain.models import SourceSystem, Policy


@dataclass
class ServiceConfig:
    """Configuration for a docker-compose service."""
    name: str
    image: str
    ports: List[str] = field(default_factory=list)
    environment: Dict[str, str] = field(default_factory=dict)
    volumes: List[str] = field(default_factory=list)
    depends_on: List[str] = field(default_factory=list)
    command: Optional[str] = None
    healthcheck: Optional[Dict[str, Any]] = None


@dataclass
class EnvVariable:
    """An environment variable definition."""
    name: str
    description: str
    default: Optional[str] = None
    required: bool = True
    secret: bool = False


def generate_docker_compose(
    services: Optional[List[ServiceConfig]] = None,
    source_system: Optional[SourceSystem] = None,
    include_db: bool = True,
    include_redis: bool = False,
    network_name: str = "integration-network",
) -> str:
    """
    Generate a docker-compose.yml file for the integration.
    
    Args:
        services: Custom service configurations
        source_system: Source system for naming
        include_db: Include PostgreSQL service
        include_redis: Include Redis service
        network_name: Docker network name
        
    Returns:
        docker-compose.yml content as string
    """
    lines = [
        "# Auto-generated docker-compose.yml",
        "# Generated by integration_coworker",
        "",
        "version: '3.8'",
        "",
        "services:",
    ]

    # Add PostgreSQL if requested
    if include_db:
        lines.extend([
            "  postgres:",
            "    image: pgvector/pgvector:pg16",
            "    container_name: integration_db",
            "    environment:",
            "      POSTGRES_USER: ${POSTGRES_USER:-integration}",
            "      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-integration}",
            "      POSTGRES_DB: ${POSTGRES_DB:-integration_db}",
            "    ports:",
            '      - "${POSTGRES_PORT:-5432}:5432"',
            "    volumes:",
            "      - postgres_data:/var/lib/postgresql/data",
            "    healthcheck:",
            '      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-integration}"]',
            "      interval: 5s",
            "      timeout: 5s",
            "      retries: 5",
            "    networks:",
            f"      - {network_name}",
            "",
        ])

    # Add Redis if requested
    if include_redis:
        lines.extend([
            "  redis:",
            "    image: redis:7-alpine",
            "    container_name: integration_redis",
            "    ports:",
            '      - "${REDIS_PORT:-6379}:6379"',
            "    volumes:",
            "      - redis_data:/data",
            "    healthcheck:",
            '      test: ["CMD", "redis-cli", "ping"]',
            "      interval: 5s",
            "      timeout: 5s",
            "      retries: 5",
            "    networks:",
            f"      - {network_name}",
            "",
        ])

    # Add custom services
    if services:
        for svc in services:
            lines.append(f"  {svc.name}:")
            lines.append(f"    image: {svc.image}")
            if svc.command:
                lines.append(f"    command: {svc.command}")

            if svc.environment:
                lines.append("    environment:")
                for key, val in svc.environment.items():
                    lines.append(f"      {key}: {val}")

            if svc.ports:
                lines.append("    ports:")
                for port in svc.ports:
                    lines.append(f'      - "{port}"')

            if svc.volumes:
                lines.append("    volumes:")
                for vol in svc.volumes:
                    lines.append(f"      - {vol}")

            if svc.depends_on:
                lines.append("    depends_on:")
                for dep in svc.depends_on:
                    lines.append(f"      - {dep}")

            if svc.healthcheck:
                lines.append("    healthcheck:")
                for key, val in svc.healthcheck.items():
                    if isinstance(val, list):
                        lines.append(f"      {key}: {val}")
                    else:
                        lines.append(f"      {key}: {val}")

            lines.append("    networks:")
            lines.append(f"      - {network_name}")
            lines.append("")

    # Add volumes section
    lines.append("volumes:")
    if include_db:
        lines.append("  postgres_data:")
    if include_redis:
        lines.append("  redis_data:")
    if services:
        for svc in services:
            for vol in svc.volumes:
                # Extract volume name from "name:/path" format
                if ":" in vol and not vol.startswith("./"):
                    vol_name = vol.split(":")[0]
                    lines.append(f"  {vol_name}:")
    lines.append("")

    # Add networks section
    lines.extend([
        "networks:",
        f"  {network_name}:",
        "    driver: bridge",
    ])

    return "\n".join(lines)


def generate_env_template(
    source_system: Optional[SourceSystem] = None,
    policies: Optional[List[Policy]] = None,
    additional_vars: Optional[List[EnvVariable]] = None,
    include_db: bool = True,
    include_llm: bool = True,
) -> str:
    """
    Generate a .env.template file with required environment variables.
    
    Args:
        source_system: Source system for API config
        policies: Policies that may require env vars
        additional_vars: Additional custom variables
        include_db: Include database variables
        include_llm: Include LLM API variables
        
    Returns:
        .env.template content as string
    """
    lines = [
        "# Integration Configuration",
        "# Generated by integration_coworker",
        "# Copy this file to .env and fill in the values",
        "",
    ]

    # Database configuration
    if include_db:
        lines.extend([
            "# Database Configuration",
            "POSTGRES_USER=integration",
            "POSTGRES_PASSWORD=changeme",
            "POSTGRES_DB=integration_db",
            "POSTGRES_HOST=localhost",
            "POSTGRES_PORT=5432",
            "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}",
            "",
        ])

    # LLM configuration
    if include_llm:
        lines.extend([
            "# LLM Configuration",
            "OPENAI_API_KEY=sk-your-openai-api-key-here",
            "# Or use Azure OpenAI:",
            "# AZURE_OPENAI_API_KEY=your-azure-key",
            "# AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com/",
            "",
        ])

    # Source system API configuration
    if source_system:
        provider_upper = source_system.code.upper()
        lines.extend([
            f"# {source_system.name} API Configuration",
        ])

        if source_system.auth_type == "bearer":
            lines.append(f"{provider_upper}_BEARER_TOKEN=your-bearer-token")
        elif source_system.auth_type == "api_key":
            lines.append(f"{provider_upper}_API_KEY=your-api-key")
        elif source_system.auth_type == "oauth2":
            lines.extend([
                f"{provider_upper}_CLIENT_ID=your-client-id",
                f"{provider_upper}_CLIENT_SECRET=your-client-secret",
                f"{provider_upper}_REDIRECT_URI=http://localhost:3000/callback",
            ])
        elif source_system.auth_type == "basic":
            lines.extend([
                f"{provider_upper}_USERNAME=your-username",
                f"{provider_upper}_PASSWORD=your-password",
            ])

        if source_system.base_url:
            lines.append(f"# {provider_upper}_BASE_URL={source_system.base_url}")
        lines.append("")

    # Policy-driven env vars
    if policies:
        policy_vars_added = False
        for policy in policies:
            if policy.policy_type == "rate_limit" and policy.config:
                if not policy_vars_added:
                    lines.append("# Rate Limiting Configuration")
                    policy_vars_added = True
                rps = policy.config.get("requests_per_second", 10)
                lines.append(f"RATE_LIMIT_RPS={rps}")
                lines.append("")

    # Additional custom variables
    if additional_vars:
        lines.append("# Application Configuration")
        for var in additional_vars:
            comment = f"# {var.description}"
            if var.required:
                comment += " (required)"
            if var.secret:
                comment += " (secret)"
            lines.append(comment)

            if var.default is not None:
                lines.append(f"{var.name}={var.default}")
            else:
                lines.append(f"{var.name}=")
        lines.append("")

    # Common app vars
    lines.extend([
        "# Application Settings",
        "LOG_LEVEL=INFO",
        "DEBUG=false",
        "",
    ])

    return "\n".join(lines)


def generate_settings_yaml(
    source_system: Optional[SourceSystem] = None,
    policies: Optional[List[Policy]] = None,
    endpoints: Optional[List[str]] = None,
) -> str:
    """
    Generate a settings.yaml configuration file.
    
    Args:
        source_system: Source system configuration
        policies: Policies to include
        endpoints: List of endpoint paths
        
    Returns:
        settings.yaml content as string
    """
    lines = [
        "# Integration Settings",
        "# Generated by integration_coworker",
        "",
        "integration:",
        "  version: '1.0'",
    ]

    if source_system:
        lines.extend([
            "",
            "  provider:",
            f"    code: {source_system.code}",
            f"    name: {source_system.name}",
        ])
        if source_system.base_url:
            lines.append(f"    base_url: ${{env:{source_system.code.upper()}_BASE_URL:{source_system.base_url}}}")
        if source_system.auth_type:
            lines.append(f"    auth_type: {source_system.auth_type}")

    if policies:
        lines.extend(["", "  policies:"])
        for policy in policies:
            lines.append(f"    - type: {policy.policy_type}")
            lines.append(f"      scope: {policy.scope}")
            if policy.config:
                lines.append("      config:")
                for key, val in policy.config.items():
                    lines.append(f"        {key}: {val}")

    if endpoints:
        lines.extend(["", "  endpoints:"])
        for ep in endpoints:
            lines.append(f"    - {ep}")

    lines.extend([
        "",
        "logging:",
        "  level: ${env:LOG_LEVEL:INFO}",
        "  format: json",
        "",
        "retry:",
        "  max_attempts: 3",
        "  backoff_factor: 2",
        "  max_delay: 60",
    ])

    return "\n".join(lines)


def generate_gitignore_additions() -> str:
    """
    Generate .gitignore additions for integration artifacts.
    
    Returns:
        .gitignore additions as string
    """
    return """
# Integration artifacts
.env
.env.local
*.bak
_integration_backups/

# Generated configs (keep .template versions)
docker-compose.override.yml
settings.local.yaml

# Secrets
**/secrets/
*.pem
*.key
"""
