"""
Code generation templates for file parsers and validators.

Provides templates and generators for creating parser code from FileSpec models.
Supports Python initially, with extensibility for other languages.
"""

from typing import Dict, List, Optional

from integration_coworker.domain.models import FileField, FileSpec


# =============================================================================
# Python Templates
# =============================================================================

PYTHON_CSV_PARSER_TEMPLATE = '''"""
Auto-generated CSV parser for {file_name}.

Generated by Integration Co-Worker File Integration V1.
"""
import csv
from dataclasses import dataclass
from typing import List, Optional
from datetime import date, datetime
from decimal import Decimal


@dataclass
class {class_name}:
    """Record from {file_name}."""
{field_definitions}


def parse_{function_name}(file_path: str) -> List[{class_name}]:
    """
    Parse {file_name} CSV file.
    
    Args:
        file_path: Path to the CSV file
        
    Returns:
        List of parsed records
        
    Raises:
        ValueError: If parsing fails for any row
    """
    records = []
    
    with open(file_path, 'r', encoding='{encoding}') as f:
        reader = csv.DictReader(f, delimiter='{delimiter}')
        
        for row_num, row in enumerate(reader, start=2):
            try:
                record = {class_name}(
{field_parsing}
                )
                records.append(record)
            except (ValueError, KeyError) as e:
                raise ValueError(f"Error parsing row {{row_num}}: {{e}}")
    
    return records


def validate_{function_name}(records: List[{class_name}]) -> List[str]:
    """
    Validate parsed records.
    
    Args:
        records: List of parsed records
        
    Returns:
        List of validation errors (empty if valid)
    """
    errors = []
    
    for i, record in enumerate(records, start=1):
{validation_code}
    
    return errors


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) != 2:
        print("Usage: python {module_name}.py <file_path>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    records = parse_{function_name}(file_path)
    print(f"Parsed {{len(records)}} records")
    
    errors = validate_{function_name}(records)
    if errors:
        print(f"Validation errors: {{len(errors)}}")
        for err in errors[:10]:
            print(f"  - {{err}}")
    else:
        print("All records valid")
'''

PYTHON_FIXED_WIDTH_PARSER_TEMPLATE = '''"""
Auto-generated fixed-width file parser for {file_name}.

Generated by Integration Co-Worker File Integration V1.
"""
from dataclasses import dataclass
from typing import List, Optional
from datetime import date, datetime
from decimal import Decimal


@dataclass
class {class_name}:
    """Record from {file_name}."""
{field_definitions}


def parse_{function_name}(file_path: str) -> List[{class_name}]:
    """
    Parse {file_name} fixed-width file.
    
    Args:
        file_path: Path to the fixed-width file
        
    Returns:
        List of parsed records
        
    Raises:
        ValueError: If parsing fails for any row
    """
    records = []
    
    with open(file_path, 'r', encoding='{encoding}') as f:
        for line_num, line in enumerate(f, start=1):
            # Skip header if present
            if line_num == 1 and {skip_header}:
                continue
            
            if not line.strip():
                continue
            
            try:
                record = {class_name}(
{fixed_width_parsing}
                )
                records.append(record)
            except (ValueError, IndexError) as e:
                raise ValueError(f"Error parsing line {{line_num}}: {{e}}")
    
    return records


def validate_{function_name}(records: List[{class_name}]) -> List[str]:
    """
    Validate parsed records.
    
    Args:
        records: List of parsed records
        
    Returns:
        List of validation errors (empty if valid)
    """
    errors = []
    
    for i, record in enumerate(records, start=1):
{validation_code}
    
    return errors
'''


# =============================================================================
# Generator Functions
# =============================================================================

def generate_csv_parser(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> str:
    """
    Generate a CSV parser for the given file spec.
    
    Args:
        file_spec: The file specification
        fields: List of fields in the file
        language: Target language (default: python)
        
    Returns:
        Generated parser code as string
        
    Raises:
        NotImplementedError: If language is not supported
    """
    if language != "python":
        raise NotImplementedError(f"Language {language} not yet supported for CSV parsers")
    
    class_name = _to_class_name(file_spec.name)
    function_name = _to_snake_case(file_spec.name)
    module_name = f"parse_{function_name}"
    
    # Generate field definitions
    field_defs = []
    for f in sorted(fields, key=lambda x: x.position):
        python_type = _to_python_type(f.field_type, f.nullable)
        field_defs.append(f"    {f.name}: {python_type}")
    
    # Generate field parsing
    field_parsing = []
    for f in sorted(fields, key=lambda x: x.position):
        parser = _get_parser_expression(f)
        field_parsing.append(f"                    {f.name}={parser},")
    
    # Generate validation code
    validation = _generate_validation_code(fields)
    
    return PYTHON_CSV_PARSER_TEMPLATE.format(
        file_name=file_spec.name,
        class_name=class_name,
        function_name=function_name,
        module_name=module_name,
        encoding=file_spec.encoding or "utf-8",
        delimiter=_escape_delimiter(file_spec.delimiter or ","),
        field_definitions="\n".join(field_defs),
        field_parsing="\n".join(field_parsing),
        validation_code=validation or "        pass  # No validation rules",
    )


def generate_fixed_width_parser(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> str:
    """
    Generate a fixed-width file parser for the given file spec.
    
    Args:
        file_spec: The file specification
        fields: List of fields with start_position and length
        language: Target language (default: python)
        
    Returns:
        Generated parser code as string
        
    Raises:
        NotImplementedError: If language is not supported
        ValueError: If fields don't have position/length info
    """
    if language != "python":
        raise NotImplementedError(f"Language {language} not yet supported for fixed-width parsers")
    
    # Validate fields have position info
    for f in fields:
        if f.start_position is None or f.length is None:
            raise ValueError(f"Field {f.name} missing start_position or length for fixed-width parsing")
    
    class_name = _to_class_name(file_spec.name)
    function_name = _to_snake_case(file_spec.name)
    
    # Generate field definitions
    field_defs = []
    for f in sorted(fields, key=lambda x: x.start_position or 0):
        python_type = _to_python_type(f.field_type, f.nullable)
        field_defs.append(f"    {f.name}: {python_type}")
    
    # Generate fixed-width parsing
    fixed_width_parsing = []
    for f in sorted(fields, key=lambda x: x.start_position or 0):
        start = f.start_position - 1  # Convert to 0-indexed
        end = start + f.length
        parser = _get_fixed_width_parser_expression(f, start, end)
        fixed_width_parsing.append(f"                    {f.name}={parser},")
    
    # Generate validation code
    validation = _generate_validation_code(fields)
    
    return PYTHON_FIXED_WIDTH_PARSER_TEMPLATE.format(
        file_name=file_spec.name,
        class_name=class_name,
        function_name=function_name,
        encoding=file_spec.encoding or "utf-8",
        skip_header=str(file_spec.has_header),
        field_definitions="\n".join(field_defs),
        fixed_width_parsing="\n".join(fixed_width_parsing),
        validation_code=validation or "        pass  # No validation rules",
    )


def generate_file_parser(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> str:
    """
    Generate appropriate parser based on file type.
    
    Convenience function that routes to the right generator.
    
    Args:
        file_spec: The file specification
        fields: List of fields
        language: Target language
        
    Returns:
        Generated parser code
    """
    if file_spec.file_type in ("csv", "tsv", "pipe_delimited", "other_delimited"):
        return generate_csv_parser(file_spec, fields, language)
    elif file_spec.file_type == "fixed_width":
        return generate_fixed_width_parser(file_spec, fields, language)
    else:
        raise NotImplementedError(f"Parser generation not supported for file type: {file_spec.file_type}")


# =============================================================================
# Helper Functions
# =============================================================================

def _to_class_name(name: str) -> str:
    """Convert to PascalCase class name."""
    # Handle snake_case and kebab-case
    parts = name.replace("-", "_").split("_")
    return "".join(word.title() for word in parts)


def _to_snake_case(name: str) -> str:
    """Convert to snake_case function name."""
    return name.replace("-", "_").lower()


def _to_python_type(field_type: str, nullable: bool) -> str:
    """Convert field type to Python type hint."""
    type_map = {
        "string": "str",
        "integer": "int",
        "decimal": "Decimal",
        "date": "date",
        "datetime": "datetime",
        "boolean": "bool",
        "email": "str",
        "uuid": "str",
        "json": "dict",
        "binary": "bytes",
    }
    base_type = type_map.get(field_type.lower(), "str")
    return f"Optional[{base_type}]" if nullable else base_type


def _get_parser_expression(field: FileField) -> str:
    """Get Python expression to parse field from CSV row dict."""
    name = field.name
    
    if field.field_type == "integer":
        if field.nullable:
            return f"int(row['{name}']) if row.get('{name}') else None"
        return f"int(row['{name}'])"
    
    if field.field_type == "decimal":
        if field.nullable:
            return f"Decimal(row['{name}']) if row.get('{name}') else None"
        return f"Decimal(row['{name}'])"
    
    if field.field_type == "date":
        # Handle common date formats
        format_mask = field.format_mask or "%Y-%m-%d"
        if field.nullable:
            return f"datetime.strptime(row['{name}'], '{format_mask}').date() if row.get('{name}') else None"
        return f"datetime.strptime(row['{name}'], '{format_mask}').date()"
    
    if field.field_type == "datetime":
        format_mask = field.format_mask or "%Y-%m-%dT%H:%M:%S"
        if field.nullable:
            return f"datetime.strptime(row['{name}'], '{format_mask}') if row.get('{name}') else None"
        return f"datetime.strptime(row['{name}'], '{format_mask}')"
    
    if field.field_type == "boolean":
        if field.nullable:
            return f"row.get('{name}', '').lower() in ('true', '1', 'yes', 'y') if row.get('{name}') else None"
        return f"row['{name}'].lower() in ('true', '1', 'yes', 'y')"
    
    # Default: string
    if field.nullable:
        return f"row.get('{name}') or None"
    return f"row['{name}']"


def _get_fixed_width_parser_expression(field: FileField, start: int, end: int) -> str:
    """Get Python expression to parse field from fixed-width line."""
    slice_expr = f"line[{start}:{end}].strip()"
    
    if field.field_type == "integer":
        if field.nullable:
            return f"int({slice_expr}) if {slice_expr} else None"
        return f"int({slice_expr})"
    
    if field.field_type == "decimal":
        if field.nullable:
            return f"Decimal({slice_expr}) if {slice_expr} else None"
        return f"Decimal({slice_expr})"
    
    if field.field_type == "date":
        format_mask = field.format_mask or "%Y%m%d"
        if field.nullable:
            return f"datetime.strptime({slice_expr}, '{format_mask}').date() if {slice_expr} else None"
        return f"datetime.strptime({slice_expr}, '{format_mask}').date()"
    
    if field.field_type == "datetime":
        format_mask = field.format_mask or "%Y%m%d%H%M%S"
        if field.nullable:
            return f"datetime.strptime({slice_expr}, '{format_mask}') if {slice_expr} else None"
        return f"datetime.strptime({slice_expr}, '{format_mask}')"
    
    if field.field_type == "boolean":
        if field.nullable:
            return f"{slice_expr}.lower() in ('y', '1', 't') if {slice_expr} else None"
        return f"{slice_expr}.lower() in ('y', '1', 't')"
    
    # Default: string
    if field.nullable:
        return f"{slice_expr} or None"
    return slice_expr


def _generate_validation_code(fields: List[FileField]) -> str:
    """Generate validation code for fields."""
    validations = []
    
    for f in fields:
        # Required field check
        if not f.nullable:
            validations.append(
                f"        if record.{f.name} is None:\n"
                f"            errors.append(f'Row {{i}}: {f.name} is required')"
            )
        
        # Regex validation
        if f.validation_regex:
            validations.append(
                f"        if record.{f.name} and not re.match(r'{f.validation_regex}', str(record.{f.name})):\n"
                f"            errors.append(f'Row {{i}}: {f.name} failed regex validation')"
            )
    
    return "\n".join(validations) if validations else ""


def _escape_delimiter(delimiter: str) -> str:
    """Escape delimiter for string literal."""
    if delimiter == "\t":
        return "\\t"
    if delimiter == "\n":
        return "\\n"
    return delimiter


__all__ = [
    "generate_csv_parser",
    "generate_fixed_width_parser",
    "generate_file_parser",
    "PYTHON_CSV_PARSER_TEMPLATE",
    "PYTHON_FIXED_WIDTH_PARSER_TEMPLATE",
]
