"""
Code generation templates for file parsers and validators.

Provides templates and generators for creating parser code from FileSpec models.
Supports Python initially, with extensibility for other languages.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional

from integration_coworker.domain.models import FileField, FileSpec, FileType


# =============================================================================
# Template Result Metadata
# =============================================================================

@dataclass
class FileParserTemplateResult:
    """
    Result of file parser generation with symbol names.
    
    This is the contract between file_templates.py and FileCodegenStrategy.
    The strategy uses these names instead of guessing symbol patterns,
    ensuring consistency between generated code and dependent artifacts
    (flows, tests).
    
    Attributes:
        code: The generated parser code
        module_basename: Base name for the module, e.g., "daily_transactions"
        record_class_name: PascalCase class name, e.g., "DailyTransactions"
        parse_func_name: Parse function name, e.g., "parse_daily_transactions"
        validate_func_name: Validate function name, e.g., "validate_daily_transactions"
        dependencies: Required packages, e.g., ["openpyxl"] for Excel
    """
    code: str
    module_basename: str
    record_class_name: str
    parse_func_name: str
    validate_func_name: str
    dependencies: List[str]


# =============================================================================
# Python Templates
# =============================================================================

PYTHON_CSV_PARSER_TEMPLATE = '''"""
Auto-generated CSV parser for {file_name}.

Generated by Integration Co-Worker File Integration V1.
"""
import csv
from dataclasses import dataclass
from typing import List, Optional
from datetime import date, datetime
from decimal import Decimal


@dataclass
class {class_name}:
    """Record from {file_name}."""
{field_definitions}


def parse_{function_name}(file_path: str) -> List[{class_name}]:
    """
    Parse {file_name} CSV file.
    
    Args:
        file_path: Path to the CSV file
        
    Returns:
        List of parsed records
        
    Raises:
        ValueError: If parsing fails for any row
    """
    records = []
    
    with open(file_path, 'r', encoding='{encoding}') as f:
        reader = csv.DictReader(f, delimiter='{delimiter}')
        
        for row_num, row in enumerate(reader, start=2):
            try:
                record = {class_name}(
{field_parsing}
                )
                records.append(record)
            except (ValueError, KeyError) as e:
                raise ValueError(f"Error parsing row {{row_num}}: {{e}}")
    
    return records


def validate_{function_name}(records: List[{class_name}]) -> List[str]:
    """
    Validate parsed records.
    
    Args:
        records: List of parsed records
        
    Returns:
        List of validation errors (empty if valid)
    """
    errors = []
    
    for i, record in enumerate(records, start=1):
{validation_code}
    
    return errors


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) != 2:
        print("Usage: python {module_name}.py <file_path>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    records = parse_{function_name}(file_path)
    print(f"Parsed {{len(records)}} records")
    
    errors = validate_{function_name}(records)
    if errors:
        print(f"Validation errors: {{len(errors)}}")
        for err in errors[:10]:
            print(f"  - {{err}}")
    else:
        print("All records valid")
'''

PYTHON_FIXED_WIDTH_PARSER_TEMPLATE = '''"""
Auto-generated fixed-width file parser for {file_name}.

Generated by Integration Co-Worker File Integration V1.
"""
from dataclasses import dataclass
from typing import List, Optional
from datetime import date, datetime
from decimal import Decimal


@dataclass
class {class_name}:
    """Record from {file_name}."""
{field_definitions}


def parse_{function_name}(file_path: str) -> List[{class_name}]:
    """
    Parse {file_name} fixed-width file.
    
    Args:
        file_path: Path to the fixed-width file
        
    Returns:
        List of parsed records
        
    Raises:
        ValueError: If parsing fails for any row
    """
    records = []
    
    with open(file_path, 'r', encoding='{encoding}') as f:
        for line_num, line in enumerate(f, start=1):
            # Skip header if present
            if line_num == 1 and {skip_header}:
                continue
            
            if not line.strip():
                continue
            
            try:
                record = {class_name}(
{fixed_width_parsing}
                )
                records.append(record)
            except (ValueError, IndexError) as e:
                raise ValueError(f"Error parsing line {{line_num}}: {{e}}")
    
    return records


def validate_{function_name}(records: List[{class_name}]) -> List[str]:
    """
    Validate parsed records.
    
    Args:
        records: List of parsed records
        
    Returns:
        List of validation errors (empty if valid)
    """
    errors = []
    
    for i, record in enumerate(records, start=1):
{validation_code}
    
    return errors
'''


PYTHON_EXCEL_PARSER_TEMPLATE = '''"""
Auto-generated Excel parser for {file_name}.

Generated by Integration Co-Worker File Integration V1.
Requires: openpyxl (pip install openpyxl)
"""
from dataclasses import dataclass
from typing import List, Optional, Dict, Any
from datetime import date, datetime
from decimal import Decimal

try:
    from openpyxl import load_workbook
except ImportError:
    raise ImportError(
        "openpyxl is required for Excel parsing. "
        "Install it with: pip install openpyxl"
    )


@dataclass
class {class_name}:
    """Record from {file_name}."""
{field_definitions}


def _normalize_header(header: str) -> str:
    """Normalize header name for matching."""
    if header is None:
        return ""
    return str(header).strip().lower().replace(" ", "_").replace("-", "_")


def _convert_value(value: Any, target_type: str, nullable: bool) -> Any:
    """Convert Excel cell value to target Python type."""
    if value is None or (isinstance(value, str) and not value.strip()):
        if nullable:
            return None
        raise ValueError(f"Non-nullable field received empty value")
    
    if target_type == "string":
        return str(value).strip()
    elif target_type == "integer":
        if isinstance(value, (int, float)):
            return int(value)
        return int(str(value).strip())
    elif target_type == "decimal":
        if isinstance(value, (int, float)):
            return Decimal(str(value))
        return Decimal(str(value).strip())
    elif target_type == "date":
        if isinstance(value, datetime):
            return value.date()
        if isinstance(value, date):
            return value
        # Try parsing string
        return datetime.strptime(str(value).strip(), "%Y-%m-%d").date()
    elif target_type == "datetime":
        if isinstance(value, datetime):
            return value
        return datetime.strptime(str(value).strip(), "%Y-%m-%dT%H:%M:%S")
    elif target_type == "boolean":
        if isinstance(value, bool):
            return value
        val_str = str(value).strip().lower()
        return val_str in ("true", "1", "yes", "y")
    else:
        return str(value).strip() if value else None


def parse_{function_name}(file_path: str, sheet_name: Optional[str] = {sheet_name_default}) -> List[{class_name}]:
    """
    Parse {file_name} Excel file.
    
    Args:
        file_path: Path to the Excel file
        sheet_name: Name of sheet to parse (default: {sheet_name_default_display})
        
    Returns:
        List of parsed records
        
    Raises:
        ValueError: If parsing fails for any row
        ImportError: If openpyxl is not installed
    """
    records = []
    
    wb = load_workbook(file_path, read_only=True, data_only=True)
    
    if sheet_name:
        if sheet_name not in wb.sheetnames:
            raise ValueError(f"Sheet '{{sheet_name}}' not found. Available: {{wb.sheetnames}}")
        ws = wb[sheet_name]
    else:
        ws = wb.active
    
    # Read all rows
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return records
    
    # First row is header
    headers = [_normalize_header(h) for h in rows[0]]
    
    # Build header -> column index mapping
    field_mapping: Dict[str, int] = {{}}
{field_mapping_code}
    
    # Parse data rows
    for row_num, row in enumerate(rows[1:], start=2):
        try:
            row_dict = {{}}
            for field_name, col_idx in field_mapping.items():
                if col_idx < len(row):
                    row_dict[field_name] = row[col_idx]
                else:
                    row_dict[field_name] = None
            
            record = {class_name}(
{field_parsing}
            )
            records.append(record)
        except (ValueError, KeyError, TypeError) as e:
            raise ValueError(f"Error parsing row {{row_num}}: {{e}}")
    
    wb.close()
    return records


def validate_{function_name}(records: List[{class_name}]) -> List[str]:
    """
    Validate parsed records.
    
    Args:
        records: List of parsed records
        
    Returns:
        List of validation errors (empty if valid)
    """
    errors = []
    
    for i, record in enumerate(records, start=1):
{validation_code}
    
    return errors


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python {module_name}.py <file_path> [sheet_name]")
        sys.exit(1)
    
    file_path = sys.argv[1]
    sheet = sys.argv[2] if len(sys.argv) > 2 else None
    
    records = parse_{function_name}(file_path, sheet_name=sheet)
    print(f"Parsed {{len(records)}} records")
    
    errors = validate_{function_name}(records)
    if errors:
        print(f"Validation errors: {{len(errors)}}")
        for err in errors[:10]:
            print(f"  - {{err}}")
    else:
        print("All records valid")
'''


# =============================================================================
# Generator Functions
# =============================================================================

def generate_csv_parser(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> str:
    """
    Generate a CSV parser for the given file spec.
    
    Args:
        file_spec: The file specification
        fields: List of fields in the file
        language: Target language (default: python)
        
    Returns:
        Generated parser code as string
        
    Raises:
        NotImplementedError: If language is not supported
    """
    if language != "python":
        raise NotImplementedError(f"Language {language} not yet supported for CSV parsers")
    
    class_name = _to_class_name(file_spec.name)
    function_name = _to_snake_case(file_spec.name)
    module_name = f"parse_{function_name}"
    
    # Generate field definitions
    field_defs = []
    for f in sorted(fields, key=lambda x: x.position):
        python_type = _to_python_type(f.field_type, f.nullable)
        field_defs.append(f"    {f.name}: {python_type}")
    
    # Generate field parsing
    field_parsing = []
    for f in sorted(fields, key=lambda x: x.position):
        parser = _get_parser_expression(f)
        field_parsing.append(f"                    {f.name}={parser},")
    
    # Generate validation code
    validation = _generate_validation_code(fields)
    
    return PYTHON_CSV_PARSER_TEMPLATE.format(
        file_name=file_spec.name,
        class_name=class_name,
        function_name=function_name,
        module_name=module_name,
        encoding=file_spec.encoding or "utf-8",
        delimiter=_escape_delimiter(file_spec.delimiter or ","),
        field_definitions="\n".join(field_defs),
        field_parsing="\n".join(field_parsing),
        validation_code=validation or "        pass  # No validation rules",
    )


def generate_fixed_width_parser(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> str:
    """
    Generate a fixed-width file parser for the given file spec.
    
    Args:
        file_spec: The file specification
        fields: List of fields with start_position and length
        language: Target language (default: python)
        
    Returns:
        Generated parser code as string
        
    Raises:
        NotImplementedError: If language is not supported
        ValueError: If fields don't have position/length info
    """
    if language != "python":
        raise NotImplementedError(f"Language {language} not yet supported for fixed-width parsers")
    
    # Validate fields have position info
    for f in fields:
        if f.start_position is None or f.length is None:
            raise ValueError(f"Field {f.name} missing start_position or length for fixed-width parsing")
    
    class_name = _to_class_name(file_spec.name)
    function_name = _to_snake_case(file_spec.name)
    
    # Generate field definitions
    field_defs = []
    for f in sorted(fields, key=lambda x: x.start_position or 0):
        python_type = _to_python_type(f.field_type, f.nullable)
        field_defs.append(f"    {f.name}: {python_type}")
    
    # Generate fixed-width parsing
    fixed_width_parsing = []
    for f in sorted(fields, key=lambda x: x.start_position or 0):
        start = f.start_position - 1  # Convert to 0-indexed
        end = start + f.length
        parser = _get_fixed_width_parser_expression(f, start, end)
        fixed_width_parsing.append(f"                    {f.name}={parser},")
    
    # Generate validation code
    validation = _generate_validation_code(fields)
    
    return PYTHON_FIXED_WIDTH_PARSER_TEMPLATE.format(
        file_name=file_spec.name,
        class_name=class_name,
        function_name=function_name,
        encoding=file_spec.encoding or "utf-8",
        skip_header=str(file_spec.has_header),
        field_definitions="\n".join(field_defs),
        fixed_width_parsing="\n".join(fixed_width_parsing),
        validation_code=validation or "        pass  # No validation rules",
    )


def generate_excel_parser(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> str:
    """
    Generate an Excel parser for the given file spec.
    
    Args:
        file_spec: The file specification
        fields: List of fields in the file
        language: Target language (default: python)
        
    Returns:
        Generated parser code as string
        
    Raises:
        NotImplementedError: If language is not supported
    """
    if language != "python":
        raise NotImplementedError(f"Language {language} not yet supported for Excel parsers")
    
    class_name = _to_class_name(file_spec.name)
    function_name = _to_snake_case(file_spec.name)
    module_name = f"parse_{function_name}"
    
    # Determine sheet name from file_spec metadata
    # Check for sheet_name in description or use None for first sheet
    sheet_name = getattr(file_spec, 'sheet_name', None)
    if sheet_name:
        sheet_name_default = f'"{sheet_name}"'
        sheet_name_default_display = f'"{sheet_name}"'
    else:
        sheet_name_default = "None"
        sheet_name_default_display = "first sheet"
    
    # Generate field definitions
    field_defs = []
    for f in sorted(fields, key=lambda x: x.position):
        python_type = _to_python_type(f.field_type, f.nullable)
        field_defs.append(f"    {f.name}: {python_type}")
    
    # Generate field mapping code (header name -> column index lookup)
    field_mapping_lines = []
    for f in sorted(fields, key=lambda x: x.position):
        normalized_name = f.name.strip().lower().replace(" ", "_").replace("-", "_")
        field_mapping_lines.append(
            f"    for idx, h in enumerate(headers):\n"
            f"        if h == '{normalized_name}':\n"
            f"            field_mapping['{f.name}'] = idx\n"
            f"            break"
        )
    field_mapping_code = "\n".join(field_mapping_lines)
    
    # Generate field parsing with type conversion
    field_parsing = []
    for f in sorted(fields, key=lambda x: x.position):
        parser = _get_excel_parser_expression(f)
        field_parsing.append(f"                {f.name}={parser},")
    
    # Generate validation code
    validation = _generate_validation_code(fields)
    
    return PYTHON_EXCEL_PARSER_TEMPLATE.format(
        file_name=file_spec.name,
        class_name=class_name,
        function_name=function_name,
        module_name=module_name,
        sheet_name_default=sheet_name_default,
        sheet_name_default_display=sheet_name_default_display,
        field_definitions="\n".join(field_defs),
        field_mapping_code=field_mapping_code,
        field_parsing="\n".join(field_parsing),
        validation_code=validation or "        pass  # No validation rules",
    )


def _normalize_file_type(file_type: str) -> str:
    """
    Normalize file type to canonical internal values.
    
    Maps common extensions and enum values to the canonical types
    used by generate_file_parser routing:
    - "csv", "tsv", "pipe_delimited", "other_delimited" -> as-is
    - "xlsx", "xls" -> "excel"
    - "fixed_width" -> as-is
    
    Args:
        file_type: Raw file type string (may be extension or enum value)
        
    Returns:
        Canonical file type string for routing
    """
    # Handle enum values
    if hasattr(file_type, 'value'):
        file_type = file_type.value
    
    file_type_lower = str(file_type).lower()
    
    # Map extensions to canonical types
    excel_types = {"xlsx", "xls", FileType.XLSX.value, FileType.XLS.value}
    if file_type_lower in excel_types:
        return "excel"
    
    return file_type_lower


def generate_file_parser(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> str:
    """
    Generate appropriate parser based on file type.
    
    Convenience function that routes to the right generator.
    
    Args:
        file_spec: The file specification
        fields: List of fields
        language: Target language
        
    Returns:
        Generated parser code
    """
    # Normalize file type to canonical values
    file_type = _normalize_file_type(file_spec.file_type)
    
    if file_type in ("csv", "tsv", "pipe_delimited", "other_delimited"):
        return generate_csv_parser(file_spec, fields, language)
    elif file_type == "fixed_width":
        return generate_fixed_width_parser(file_spec, fields, language)
    elif file_type == "excel":
        return generate_excel_parser(file_spec, fields, language)
    else:
        raise NotImplementedError(f"Parser generation not supported for file type: {file_spec.file_type}")


def generate_file_parser_with_metadata(
    file_spec: FileSpec,
    fields: List[FileField],
    language: str = "python",
) -> FileParserTemplateResult:
    """
    Generate parser code with metadata about generated symbols.
    
    This is the preferred API for FileCodegenStrategy - it returns both the
    generated code AND the symbol names used, so dependent artifacts (flows,
    tests) can reference them without guessing.
    
    File types are normalized: "xlsx"/"xls" -> "excel" for routing.
    
    Args:
        file_spec: The file specification
        fields: List of fields
        language: Target language
        
    Returns:
        FileParserTemplateResult with code and symbol names
        
    Raises:
        NotImplementedError: If file type is not supported
    """
    # Generate the code using existing function (which handles normalization)
    code = generate_file_parser(file_spec, fields, language)
    
    # Use the same naming helpers that templates use internally
    module_basename = _to_snake_case(file_spec.name)
    class_name = _to_class_name(file_spec.name)
    parse_func = f"parse_{module_basename}"
    validate_func = f"validate_{module_basename}"
    
    # Determine dependencies based on normalized file type
    dependencies: List[str] = []
    normalized_type = _normalize_file_type(file_spec.file_type)
    
    if normalized_type == "excel":
        dependencies.append("openpyxl")
    
    return FileParserTemplateResult(
        code=code,
        module_basename=module_basename,
        record_class_name=class_name,
        parse_func_name=parse_func,
        validate_func_name=validate_func,
        dependencies=dependencies,
    )


# =============================================================================
# Helper Functions
# =============================================================================

def _to_class_name(name: str) -> str:
    """Convert to PascalCase class name."""
    # Handle snake_case and kebab-case
    parts = name.replace("-", "_").split("_")
    return "".join(word.title() for word in parts)


def _to_snake_case(name: str) -> str:
    """Convert to snake_case function name."""
    return name.replace("-", "_").lower()


def _to_python_type(field_type: str, nullable: bool) -> str:
    """Convert field type to Python type hint."""
    type_map = {
        "string": "str",
        "integer": "int",
        "decimal": "Decimal",
        "date": "date",
        "datetime": "datetime",
        "boolean": "bool",
        "email": "str",
        "uuid": "str",
        "json": "dict",
        "binary": "bytes",
    }
    base_type = type_map.get(field_type.lower(), "str")
    return f"Optional[{base_type}]" if nullable else base_type


def _get_parser_expression(field: FileField) -> str:
    """Get Python expression to parse field from CSV row dict."""
    name = field.name
    
    if field.field_type == "integer":
        if field.nullable:
            return f"int(row['{name}']) if row.get('{name}') else None"
        return f"int(row['{name}'])"
    
    if field.field_type == "decimal":
        if field.nullable:
            return f"Decimal(row['{name}']) if row.get('{name}') else None"
        return f"Decimal(row['{name}'])"
    
    if field.field_type == "date":
        # Handle common date formats
        format_mask = field.format_mask or "%Y-%m-%d"
        if field.nullable:
            return f"datetime.strptime(row['{name}'], '{format_mask}').date() if row.get('{name}') else None"
        return f"datetime.strptime(row['{name}'], '{format_mask}').date()"
    
    if field.field_type == "datetime":
        format_mask = field.format_mask or "%Y-%m-%dT%H:%M:%S"
        if field.nullable:
            return f"datetime.strptime(row['{name}'], '{format_mask}') if row.get('{name}') else None"
        return f"datetime.strptime(row['{name}'], '{format_mask}')"
    
    if field.field_type == "boolean":
        if field.nullable:
            return f"row.get('{name}', '').lower() in ('true', '1', 'yes', 'y') if row.get('{name}') else None"
        return f"row['{name}'].lower() in ('true', '1', 'yes', 'y')"
    
    # Default: string
    if field.nullable:
        return f"row.get('{name}') or None"
    return f"row['{name}']"


def _get_fixed_width_parser_expression(field: FileField, start: int, end: int) -> str:
    """Get Python expression to parse field from fixed-width line."""
    slice_expr = f"line[{start}:{end}].strip()"
    
    if field.field_type == "integer":
        if field.nullable:
            return f"int({slice_expr}) if {slice_expr} else None"
        return f"int({slice_expr})"
    
    if field.field_type == "decimal":
        if field.nullable:
            return f"Decimal({slice_expr}) if {slice_expr} else None"
        return f"Decimal({slice_expr})"
    
    if field.field_type == "date":
        format_mask = field.format_mask or "%Y%m%d"
        if field.nullable:
            return f"datetime.strptime({slice_expr}, '{format_mask}').date() if {slice_expr} else None"
        return f"datetime.strptime({slice_expr}, '{format_mask}').date()"
    
    if field.field_type == "datetime":
        format_mask = field.format_mask or "%Y%m%d%H%M%S"
        if field.nullable:
            return f"datetime.strptime({slice_expr}, '{format_mask}') if {slice_expr} else None"
        return f"datetime.strptime({slice_expr}, '{format_mask}')"
    
    if field.field_type == "boolean":
        if field.nullable:
            return f"{slice_expr}.lower() in ('y', '1', 't') if {slice_expr} else None"
        return f"{slice_expr}.lower() in ('y', '1', 't')"
    
    # Default: string
    if field.nullable:
        return f"{slice_expr} or None"
    return slice_expr


def _get_excel_parser_expression(field: FileField) -> str:
    """Get Python expression to parse field from Excel row_dict using _convert_value."""
    name = field.name
    field_type = field.field_type or "string"
    nullable = "True" if field.nullable else "False"
    return f"_convert_value(row_dict.get('{name}'), '{field_type}', {nullable})"


def _generate_validation_code(fields: List[FileField]) -> str:
    """Generate validation code for fields."""
    validations = []
    
    for f in fields:
        # Required field check
        if not f.nullable:
            validations.append(
                f"        if record.{f.name} is None:\n"
                f"            errors.append(f'Row {{i}}: {f.name} is required')"
            )
        
        # Regex validation
        if f.validation_regex:
            validations.append(
                f"        if record.{f.name} and not re.match(r'{f.validation_regex}', str(record.{f.name})):\n"
                f"            errors.append(f'Row {{i}}: {f.name} failed regex validation')"
            )
    
    return "\n".join(validations) if validations else ""


def _escape_delimiter(delimiter: str) -> str:
    """Escape delimiter for string literal."""
    if delimiter == "\t":
        return "\\t"
    if delimiter == "\n":
        return "\\n"
    return delimiter


__all__ = [
    "generate_csv_parser",
    "generate_fixed_width_parser",
    "generate_excel_parser",
    "generate_file_parser",
    "PYTHON_CSV_PARSER_TEMPLATE",
    "PYTHON_FIXED_WIDTH_PARSER_TEMPLATE",
    "PYTHON_EXCEL_PARSER_TEMPLATE",
]
